import "react-native-url-polyfill/auto";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Location from "expo-location";
import { createClient, type Session } from "@supabase/supabase-js";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";

const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL ?? "";
const supabaseAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? "";
const apiBase = (process.env.EXPO_PUBLIC_API_BASE_URL ?? "").replace(/\/$/, "");
const supabase = createClient(supabaseUrl, supabaseAnonKey, { auth: { storage: AsyncStorage, autoRefreshToken: true, persistSession: true, detectSessionInUrl: false } });

type Rider = { id: string; status?: string|null; vehicle_type?: string|null; vehicle_plate?: string|null; is_online?: boolean };
type Assignment = { id: string; delivery_id: string; rider_id: string; status?: string|null; offered_at?: string };
type Delivery = { id: string; master_order_id: string; delivery_address_text: string; delivery_latitude?: number|null; delivery_longitude?: number|null; status?: string|null; eta_seconds?: number|null };
type Slot = { id: string; slot_date: string; start_time: string; end_time: string; capacity: number; status: string };
type Earnings = { total_minor?: number; pending_minor?: number; paid_minor?: number } | null;

async function api<T>(session: Session, path: string, options: RequestInit = {}): Promise<T> {
  const response = await fetch(apiBase + "/api/v1/" + path, { ...options, headers: { Accept: "application/json", Authorization: "Bearer " + session.access_token, ...(options.body ? { "Content-Type": "application/json" } : {}), ...(options.headers ?? {}) } });
  const payload = await response.json() as { success?: boolean; data?: T; error?: { message?: string } };
  if (!response.ok || !payload.success) throw new Error(payload.error?.message ?? "API request failed.");
  return payload.data as T;
}
function Button({title,onPress,disabled=false}:{title:string;onPress:()=>void;disabled?:boolean}) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button,disabled&&styles.disabled]}><Text style={styles.buttonText}>{title}</Text></Pressable>; }
function money(minor:number|undefined){return ((minor??0)/100).toFixed(2)+" DH";}

function Login({onSession}:{onSession:(s:Session)=>void}) {
  const[email,setEmail]=useState(""); const[password,setPassword]=useState(""); const[busy,setBusy]=useState(false); const[error,setError]=useState("");
  async function submit(){setBusy(true);setError("");const r=await supabase.auth.signInWithPassword({email:email.trim(),password});if(r.error)setError(r.error.message);else if(r.data.session)onSession(r.data.session);setBusy(false);}
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.login}><View style={styles.brand}><Text style={styles.logo}>W</Text><View><Text style={styles.kicker}>WASSLHA RIDER</Text><Text style={styles.brandTitle}>Delivery Partner</Text></View></View><Text style={styles.title}>خدم بذكاء. ربح أكثر.</Text><Text style={styles.muted}>استقبل العروض، اختار الخدمة، وتابع التوصيل من نفس التطبيق.</Text><TextInput autoCapitalize="none" keyboardType="email-address" placeholder="البريد الإلكتروني" value={email} onChangeText={setEmail} style={styles.input}/><TextInput secureTextEntry placeholder="كلمة المرور" value={password} onChangeText={setPassword} style={styles.input}/>{error?<Text style={styles.error}>{error}</Text>:null}<Button title={busy?"جارِ الدخول...":"دخول"} onPress={submit} disabled={busy||!email||!password}/></ScrollView></SafeAreaView>;
}

export default function App(){
  const[session,setSession]=useState<Session|null>(null); const[ready,setReady]=useState(false);
  useEffect(()=>{let mounted=true;(async()=>{if(!supabaseUrl||!supabaseAnonKey){setReady(true);return}const r=await supabase.auth.getSession();if(mounted){setSession(r.data.session);setReady(true)}})();const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>{mounted=false;subscription.unsubscribe()}},[]);
  if(!ready)return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator/></View></SafeAreaView>;
  if(!supabaseUrl||!supabaseAnonKey||!apiBase)return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.error}>Configuration EXPO_PUBLIC_SUPABASE_* / EXPO_PUBLIC_API_BASE_URL ناقصة.</Text></View></SafeAreaView>;
  return session?<RiderHome session={session}/>:<Login onSession={setSession}/>;
}

function RiderHome({session}:{session:Session}){
  const[rider,setRider]=useState<Rider|null>(null); const[assignments,setAssignments]=useState<Assignment[]>([]); const[deliveries,setDeliveries]=useState<Delivery[]>([]); const[slots,setSlots]=useState<Slot[]>([]); const[earnings,setEarnings]=useState<Earnings>(null); const[tab,setTab]=useState<"home"|"orders"|"slots"|"earnings">("home"); const[loading,setLoading]=useState(true); const[locationState,setLocationState]=useState<"off"|"starting"|"live">("off");
  async function load(){setLoading(true);try{const[a,b,c,d,e]=await Promise.all([api<Rider>(session,"rider/me"),api<Assignment[]>(session,"rider/me/assignments"),api<Delivery[]>(session,"rider/me/deliveries"),api<Slot[]>(session,"rider-slots"),api<Earnings>(session,"rider/me/earnings")]);setRider(a);setAssignments(b);setDeliveries(c);setSlots(d);setEarnings(e)}catch(e){Alert.alert("WASSLHA",e instanceof Error?e.message:"تعذر تحميل البيانات.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  useEffect(()=>{let cancelled=false;let watcher:Location.LocationSubscription|undefined;(async()=>{if(!rider?.is_online){setLocationState("off");return}setLocationState("starting");const permission=await Location.requestForegroundPermissionsAsync();if(cancelled||permission.status!=="granted"){setLocationState("off");return}watcher=await Location.watchPositionAsync({accuracy:Location.Accuracy.High,distanceInterval:25,timeInterval:10000},async pos=>{try{const active=assignments.find(a=>a.status==="accepted");await api(session,"rider/me/location",{method:"POST",body:JSON.stringify({delivery_id:active?.delivery_id??null,latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy_meters:pos.coords.accuracy,speed_mps:pos.coords.speed,heading:pos.coords.heading})});setLocationState("live")}catch{setLocationState("off")}})})();return()=>{cancelled=true;watcher?.remove()}},[rider?.is_online,session,assignments]);
  async function toggleOnline(value:boolean){try{setRider(await api<Rider>(session,"rider/me/online",{method:"POST",body:JSON.stringify({is_online:value})}))}catch(e){Alert.alert("WASSLHA",e instanceof Error?e.message:"تعذر تغيير الحالة.")}}
  async function respond(id:string,status:"accepted"|"rejected"){try{await api(session,"rider/me/assignments/"+id+"/respond",{method:"POST",body:JSON.stringify({status})});await load()}catch(e){Alert.alert("WASSLHA",e instanceof Error?e.message:"تعذر الرد على العرض.")}}
  async function join(slotId:string){try{await api(session,"rider-slots/"+slotId+"/waitlist",{method:"POST"});Alert.alert("تم","تم تسجيلك في قائمة الانتظار.");await load()}catch(e){Alert.alert("WASSLHA",e instanceof Error?e.message:"تعذر الانضمام.")}}
  const deliveryById=useMemo(()=>new Map(deliveries.map(d=>[d.id,d])),[deliveries]); const active=assignments.find(a=>a.status==="accepted"); const activeDelivery=active?deliveryById.get(active.delivery_id):undefined;
  function navigate(delivery?:Delivery){if(delivery?.delivery_latitude==null||delivery?.delivery_longitude==null){Alert.alert("الموقع غير متوفر","لا توجد إحداثيات للوجهة حالياً.");return}void Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${delivery.delivery_latitude},${delivery.delivery_longitude}&travelmode=driving`)}
  if(loading)return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator/></View></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.kicker}>WASSLHA RIDER</Text><Text style={styles.headerTitle}>مرحباً بالسائق</Text></View><View style={styles.onlineWrap}><Text style={styles.muted}>{rider?.is_online?locationState==="live"?"GPS مباشر":"متصل":"غير متصل"}</Text><Switch value={!!rider?.is_online} onValueChange={toggleOnline}/></View></View><ScrollView contentContainerStyle={styles.content}>
    {activeDelivery?<View style={styles.hero}><View style={styles.heroTop}><View><Text style={styles.heroLabel}>التوصيلة الحالية</Text><Text style={styles.heroTitle}>{activeDelivery.status??"accepted"}</Text></View><Text style={styles.live}>{locationState==="live"?"● LIVE":"○ GPS"}</Text></View><Text style={styles.address}>{activeDelivery.delivery_address_text}</Text><View style={styles.row}><Button title="فتح Navigation" onPress={()=>navigate(activeDelivery)}/><Text style={styles.muted}>{activeDelivery.eta_seconds?Math.round(activeDelivery.eta_seconds/60)+" د ETA":"ETA —"}</Text></View></View>:null}
    {tab==="home"&&<><View style={styles.stats}><Stat value={String(assignments.filter(x=>x.status==="offered").length)} label="عروض جديدة"/><Stat value={String(deliveries.length)} label="توصيلات"/><Stat value={money(earnings?.total_minor)} label="الأرباح"/></View><Text style={styles.section}>العروض الجديدة</Text>{assignments.filter(x=>x.status==="offered").slice(0,4).map(a=><AssignmentCard key={a.id} assignment={a} delivery={deliveryById.get(a.delivery_id)} onRespond={respond} onNavigate={navigate}/>)}</>}
    {tab==="orders"&&<><Text style={styles.section}>العروض والتوصيلات</Text><FlatList scrollEnabled={false} data={assignments} keyExtractor={x=>x.id} renderItem={({item})=><AssignmentCard assignment={item} delivery={deliveryById.get(item.delivery_id)} onRespond={respond} onNavigate={navigate}/>} ListEmptyComponent={<Text style={styles.muted}>لا توجد توصيلات حالياً.</Text>}/></>}
    {tab==="slots"&&<><Text style={styles.section}>Slots</Text>{slots.map(item=><View style={styles.card} key={item.id}><View style={styles.row}><Text style={styles.cardTitle}>{item.slot_date}</Text><Text style={styles.badge}>{item.status}</Text></View><Text style={styles.muted}>{item.start_time} → {item.end_time} · السعة {item.capacity}</Text><Button title="قائمة الانتظار" onPress={()=>void join(item.id)}/></View>)}</>}
    {tab==="earnings"&&<><Text style={styles.section}>الأرباح</Text><View style={styles.earningsCard}><Text style={styles.muted}>إجمالي الأرباح</Text><Text style={styles.bigMoney}>{money(earnings?.total_minor)}</Text><View style={styles.row}><View><Text style={styles.muted}>قيد التسوية</Text><Text style={styles.cardTitle}>{money(earnings?.pending_minor)}</Text></View><View><Text style={styles.muted}>مدفوع</Text><Text style={styles.cardTitle}>{money(earnings?.paid_minor)}</Text></View></View></View></>}
  </ScrollView><View style={styles.tabs}>{([["home","الرئيسية"],["orders","الطلبات"],["slots","Slots"],["earnings","الأرباح"]] as const).map(([key,label])=><Pressable key={key} onPress={()=>setTab(key)}><Text style={tab===key?styles.tabActive:styles.tab}>{label}</Text></Pressable>)}<Pressable onPress={()=>void supabase.auth.signOut()}><Text style={styles.tab}>خروج</Text></Pressable></View></SafeAreaView>;
}
function Stat({value,label}:{value:string;label:string}){return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.muted}>{label}</Text></View>}
function AssignmentCard({assignment,delivery,onRespond,onNavigate}:{assignment:Assignment;delivery?:Delivery;onRespond:(id:string,status:"accepted"|"rejected")=>Promise<void>;onNavigate:(delivery?:Delivery)=>void}){return <View style={styles.card}><View style={styles.row}><Text style={styles.cardTitle}>طلب توصيل</Text><Text style={styles.badge}>{assignment.status??"unknown"}</Text></View>{delivery?<><Text style={styles.address}>{delivery.delivery_address_text}</Text><Text style={styles.muted}>{delivery.status??"—"}{delivery.eta_seconds?" · "+Math.round(delivery.eta_seconds/60)+" د":""}</Text></>:null}{assignment.status==="offered"?<View style={styles.row}><Button title="قبول" onPress={()=>void onRespond(assignment.id,"accepted")}/><Button title="رفض" onPress={()=>void onRespond(assignment.id,"rejected")}/></View>:assignment.status==="accepted"?<Button title="فتح Navigation" onPress={()=>onNavigate(delivery)}/>:null}</View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#f4f6f8"},login:{flexGrow:1,justifyContent:"center",padding:24},center:{flex:1,alignItems:"center",justifyContent:"center",padding:24},brand:{flexDirection:"row",alignItems:"center",gap:12,marginBottom:24},logo:{width:54,height:54,borderRadius:16,backgroundColor:"#101827",color:"#fff",textAlign:"center",textAlignVertical:"center",fontSize:28,fontWeight:"900"},brandTitle:{fontSize:20,fontWeight:"900",color:"#172033"},kicker:{fontSize:11,fontWeight:"800",letterSpacing:1.5,color:"#64748b"},title:{fontSize:30,fontWeight:"900",color:"#172033",marginVertical:8},headerTitle:{fontSize:23,fontWeight:"900",color:"#172033",marginTop:4},muted:{color:"#64748b",lineHeight:20},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#d7dee8",borderRadius:12,padding:13,marginTop:12},button:{backgroundColor:"#172033",borderRadius:11,paddingVertical:11,paddingHorizontal:15,marginTop:12,alignSelf:"flex-start"},buttonText:{color:"#fff",fontWeight:"800"},disabled:{opacity:.45},error:{color:"#9f1239",backgroundColor:"#fff1f2",padding:12,borderRadius:10,marginTop:12},header:{padding:18,paddingTop:24,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},onlineWrap:{flexDirection:"row",alignItems:"center",gap:6},content:{padding:18,paddingBottom:110},hero:{backgroundColor:"#172033",borderRadius:20,padding:18,marginBottom:16},heroTop:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start"},heroLabel:{color:"#cbd5e1",fontSize:12,fontWeight:"800"},heroTitle:{color:"#fff",fontSize:24,fontWeight:"900",marginTop:4},live:{color:"#86efac",fontWeight:"900"},stats:{flexDirection:"row",gap:10,marginBottom:22},stat:{flex:1,backgroundColor:"#fff",borderWidth:1,borderColor:"#e5eaf0",borderRadius:15,padding:14},statValue:{fontSize:21,fontWeight:"900",color:"#172033"},section:{fontSize:19,fontWeight:"900",color:"#172033",marginBottom:12},card:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e5eaf0",borderRadius:16,padding:16,marginBottom:12},cardTitle:{fontSize:16,fontWeight:"800",color:"#172033"},row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},address:{fontSize:15,fontWeight:"800",color:"#172033",marginTop:10},badge:{paddingVertical:4,paddingHorizontal:8,borderRadius:99,backgroundColor:"#eef2f7",fontSize:11,fontWeight:"800",color:"#475569"},earningsCard:{backgroundColor:"#fff",borderRadius:20,padding:20},bigMoney:{fontSize:34,fontWeight:"900",color:"#172033",marginVertical:8},tabs:{position:"absolute",bottom:0,left:0,right:0,backgroundColor:"#fff",borderTopWidth:1,borderTopColor:"#e5eaf0",padding:12,flexDirection:"row",justifyContent:"space-around"},tab:{color:"#64748b",fontWeight:"700"},tabActive:{color:"#172033",fontWeight:"900"}});
