import {useEffect,useState,type FormEvent,type ReactNode} from "react";
import {createProduct,createStore,getDashboard,updateProduct,updateStore,updateSubOrderStatus,type Dashboard,type Product,type Settlement,type Store,type SubOrder} from "./lib/api";
import {session,signIn,signOut,supabase} from "./lib/auth";
function money(v:number|string){return (Number(v)/100).toLocaleString("fr-MA",{minimumFractionDigits:2,maximumFractionDigits:2})+" MAD"}
function Login({done}:{done:()=>void}){const[e,setE]=useState("");const[p,setP]=useState("");const[busy,setBusy]=useState(false);const[err,setErr]=useState("");async function submit(x:FormEvent){x.preventDefault();setBusy(true);setErr("");const r=await signIn(e.trim(),p);if(r.error)setErr(r.error);else done();setBusy(false)}return <main className="login"><form onSubmit={submit}><div className="logo">W</div><span className="kicker">WASSLHA MERCHANT</span><h1>لوحة التاجر</h1><p>إدارة المتجر والطلبات والمنتجات والأرباح من مكان واحد.</p><label>Email<input type="email" value={e} onChange={x=>setE(x.target.value)} required/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} required/></label>{err&&<div className="error">{err}</div>}<button disabled={busy}>{busy?"جارِ الدخول...":"دخول"}</button></form></main>}
function App(){const[sessionReady,setSessionReady]=useState(false);const[authorized,setAuthorized]=useState(false);const[data,setData]=useState<Dashboard|null>(null);const[token,setToken]=useState("");const[busyOrder,setBusyOrder]=useState<string|null>(null);const[tab,setTab]=useState("overview");const[err,setErr]=useState("");const[editingProduct,setEditingProduct]=useState<Product|null>(null);const[editingStore,setEditingStore]=useState<Store|null>(null);const[busy,setBusy]=useState(false);
useEffect(()=>{void (async()=>{const s=await session();setSessionReady(true);if(!s)return;try{setToken(s.access_token);setData(await getDashboard(s.access_token));setAuthorized(true)}catch(e){setErr(e instanceof Error?e.message:"Merchant access denied.")}})()},[]);
async function load(){const s=await session();if(!s)return;try{setToken(s.access_token);setData(await getDashboard(s.access_token));setAuthorized(true);setErr("")}catch(e){setErr(e instanceof Error?e.message:"Unable to load dashboard.")}}
if(!sessionReady)return <main className="login"><div className="loading">جارِ التحقق...</div></main>;
if(!authorized)return <Login done={load}/>;
if(!data)return <main className="login"><div className="error">{err||"Merchant account not found."}</div></main>;
const pending=data.orders.filter(o=>["pending","confirmed","preparing"].includes(o.status)).length;
const revenue=data.settlements.reduce((n,s)=>n+Number(s.net_amount_minor),0);
return <div className="shell"><aside><div className="brand"><span className="logo">W</span><div><b>WASSLHA</b><small>Merchant</small></div></div><nav>{[["overview","الرئيسية"],["orders","الطلبات"],["products","المنتجات"],["stores","المتاجر"],["earnings","الأرباح"]].map(([k,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav><button className="logout" onClick={async()=>{await signOut();location.reload()}}>خروج</button></aside><main className="content"><header><div><span className="kicker">MERCHANT CONTROL CENTER</span><h1>{tab==="overview"?"نظرة عامة":tab==="orders"?"الطلبات":tab==="products"?"المنتجات":tab==="stores"?"المتاجر":"الأرباح"}</h1></div><button className="refresh" onClick={load}>تحديث</button></header>{err&&<div className="error">{err}</div>}{tab==="overview"&&<><section className="cards"><article><span>الطلبات النشيطة</span><b>{pending}</b><small>من آخر 100 طلب</small></article><article><span>المنتجات</span><b>{data.products.length}</b><small>الحالة الحالية</small></article><article><span>المتاجر</span><b>{data.stores.length}</b><small>{data.stores.filter(s=>s.is_active).length} نشطة</small></article><article><span>صافي التسويات</span><b>{money(revenue)}</b><small>حسب settlement records</small></article></section><section className="panel"><h2>آخر الطلبات</h2><Orders rows={data.orders.slice(0,8)} busyOrder={busyOrder} onStatus={async(id,status)=>{setBusyOrder(id);try{await updateSubOrderStatus(token,id,status);await load()}catch(e){setErr(e instanceof Error?e.message:"Unable to update order.")}finally{setBusyOrder(null)}}}/></section></>}{tab==="orders"&&<section className="panel"><h2>طلبات المتجر</h2><Orders rows={data.orders} busyOrder={busyOrder} onStatus={async(id,status)=>{setBusyOrder(id);try{await updateSubOrderStatus(token,id,status);await load()}catch(e){setErr(e instanceof Error?e.message:"Unable to update order.")}finally{setBusyOrder(null)}}}/></section>}{tab==="products"&&<section className="panel"><h2>المنتجات</h2><Products rows={data.products} stores={data.stores} token={token} editing={editingProduct} setEditing={setEditingProduct} busy={busy} setBusy={setBusy} reload={load}/></section>}{tab==="stores"&&<section className="panel"><h2>المتاجر</h2><Stores rows={data.stores} token={token} editing={editingStore} setEditing={setEditingStore} busy={busy} setBusy={setBusy} reload={load}/></section>}{tab==="earnings"&&<section className="panel"><h2>التسويات المالية</h2><Settlements rows={data.settlements}/></section>}</main></div>}
function Orders({rows,busyOrder,onStatus}:{rows:SubOrder[];busyOrder:string|null;onStatus:(id:string,status:string)=>Promise<void>}){return <Table headers={["الطلب","الحالة","المجموع","التاريخ","الإجراء"]}>{rows.map(r=><tr key={r.id}><td><b>{r.sub_order_number}</b></td><td><span className="badge">{r.status}</span></td><td>{money(r.total_minor)}</td><td>{new Date(r.created_at).toLocaleString("fr-MA")}</td><td><OrderActions row={r} busy={busyOrder===r.id} onStatus={onStatus}/></td></tr>)}</Table>}
function OrderActions({row,busy,onStatus}:{row:SubOrder;busy:boolean;onStatus:(id:string,status:string)=>Promise<void>}){const next=row.status==="pending"?["confirmed","cancelled"]:row.status==="confirmed"?["preparing","cancelled"]:row.status==="preparing"?["ready_for_pickup","cancelled"]:[];return next.length?<div className="actions">{next.map(s=><button key={s} disabled={busy} onClick={()=>onStatus(row.id,s)}>{busy?"...":s}</button>)}</div>:<span>—</span>}
function Products({rows,stores,token,editing,setEditing,busy,setBusy,reload}:{rows:Product[];stores:Store[];token:string;editing:Product|null;setEditing:(v:Product|null)=>void;busy:boolean;setBusy:(v:boolean)=>void;reload:()=>Promise<void>}){const[createOpen,setCreateOpen]=useState(false);return <><div className="toolbar"><button onClick={()=>setCreateOpen(true)}>+ منتج جديد</button></div>{createOpen&&<ProductForm stores={stores} token={token} busy={busy} setBusy={setBusy} reload={reload} close={()=>setCreateOpen(false)}/>} {editing&&<ProductForm product={editing} stores={stores} token={token} busy={busy} setBusy={setBusy} reload={reload} close={()=>setEditing(null)}/>}<Table headers={["المنتج","السعر","المخزون","الظهور","الموافقة",""]}>{rows.map(r=><tr key={r.id}><td><b>{r.name_ar}</b><small>{r.name_fr}</small></td><td>{money(r.price_minor)}</td><td>{r.stock_quantity} {r.stock_unit}</td><td>{r.is_active&&r.is_available?"متاح":"غير متاح"}</td><td><span className="badge">{r.approval_status}</span></td><td><button onClick={()=>setEditing(r)}>تعديل</button></td></tr>)}</Table></>}

function ProductForm({product,stores,token,busy,setBusy,reload,close}:{product?:Product;stores:Store[];token:string;busy:boolean;setBusy:(v:boolean)=>void;reload:()=>Promise<void>;close:()=>void}){const[storeId,setStoreId]=useState(product?.store_id??stores[0]?.id??"");const[nameAr,setNameAr]=useState(product?.name_ar??"");const[nameFr,setNameFr]=useState(product?.name_fr??"");const[price,setPrice]=useState(product?String(product.price_minor/100):"");const[stock,setStock]=useState(product?String(product.stock_quantity):"");const[unit,setUnit]=useState(product?.stock_unit??"piece");const[available,setAvailable]=useState(product?.is_available??true);const[active,setActive]=useState(product?.is_active??true);const[error,setError]=useState("");async function save(){setError("");const priceMajor=Number(price);const stockN=Number(stock);if(!storeId||!nameAr.trim()||!nameFr.trim()||!Number.isFinite(priceMajor)||priceMajor<0||!Number.isInteger(stockN)||stockN<0){setError("تحقق من الحقول المطلوبة.");return}setBusy(true);try{const input={name_ar:nameAr.trim(),name_fr:nameFr.trim(),price_minor:Math.round(priceMajor*100),stock_quantity:stockN,stock_unit:unit.trim()||"piece",is_available:available,is_active:active};if(product)await updateProduct(token,product.id,storeId,input);else await createProduct(token,storeId,{...input,approval_status:"pending"});await reload();close()}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ المنتج.")}finally{setBusy(false)}}return <div className="editor"><h3>{product?"تعديل المنتج":"إضافة منتج"}</h3><div className="form-grid">{!product&&<label>المتجر<select value={storeId} onChange={e=>setStoreId(e.target.value)}>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}<label>الاسم بالعربية<input value={nameAr} onChange={e=>setNameAr(e.target.value)}/></label><label>الاسم بالفرنسية<input value={nameFr} onChange={e=>setNameFr(e.target.value)}/></label><label>السعر MAD<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>المخزون<input type="number" min="0" step="1" value={stock} onChange={e=>setStock(e.target.value)}/></label><label>الوحدة<input value={unit} onChange={e=>setUnit(e.target.value)}/></label><label className="check"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/> متاح للطلب</label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> نشط</label></div>{error&&<div className="error">{error}</div>}<div className="actions"><button disabled={busy} onClick={save}>{busy?"...":"حفظ"}</button><button disabled={busy} onClick={close}>إلغاء</button></div></div>}

function Stores({rows,token,editing,setEditing,busy,setBusy,reload}:{rows:Store[];token:string;editing:Store|null;setEditing:(v:Store|null)=>void;busy:boolean;setBusy:(v:boolean)=>void;reload:()=>Promise<void>}){const[createOpen,setCreateOpen]=useState(false);return <><div className="toolbar"><button onClick={()=>setCreateOpen(true)}>+ متجر جديد</button></div>{createOpen&&<StoreForm token={token} busy={busy} setBusy={setBusy} reload={reload} close={()=>setCreateOpen(false)}/>} {editing&&<StoreForm store={editing} token={token} busy={busy} setBusy={setBusy} reload={reload} close={()=>setEditing(null)}/>}<Table headers={["المتجر","العنوان","نشط","استقبال الطلبات",""]}>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.address_text}</td><td>{r.is_active?"نعم":"لا"}</td><td>{r.is_accepting_orders?"نعم":"متوقف"}</td><td><button onClick={()=>setEditing(r)}>تعديل</button></td></tr>)}</Table></>}

function StoreForm({store,token,busy,setBusy,reload,close}:{store?:Store;token:string;busy:boolean;setBusy:(v:boolean)=>void;reload:()=>Promise<void>;close:()=>void}){const[name,setName]=useState(store?.name??"");const[address,setAddress]=useState(store?.address_text??"");const[phone,setPhone]=useState(store?.phone??"");const[description,setDescription]=useState(store?.description??"");const[active,setActive]=useState(store?.is_active??true);const[accepting,setAccepting]=useState(store?.is_accepting_orders??true);const[error,setError]=useState("");async function save(){setError("");if(!name.trim()||!address.trim()){setError("اسم المتجر والعنوان مطلوبان.");return}setBusy(true);try{const input={name:name.trim(),address_text:address.trim(),phone:phone.trim()||null,description:description.trim()||null,is_active:active,is_accepting_orders:accepting};if(store)await updateStore(token,store.id,input);else await createStore(token,input);await reload();close()}catch(e){setError(e instanceof Error?e.message:"تعذر حفظ المتجر.")}finally{setBusy(false)}}return <div className="editor"><h3>{store?"تعديل المتجر":"إضافة متجر"}</h3><div className="form-grid"><label>الاسم<input value={name} onChange={e=>setName(e.target.value)}/></label><label>العنوان<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label>الهاتف<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>الوصف<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> نشط</label><label className="check"><input type="checkbox" checked={accepting} onChange={e=>setAccepting(e.target.checked)}/> استقبال الطلبات</label></div>{error&&<div className="error">{error}</div>}<div className="actions"><button disabled={busy} onClick={save}>{busy?"...":"حفظ"}</button><button disabled={busy} onClick={close}>إلغاء</button></div></div>}
function Stores({rows}:{rows:Store[]}){return <Table headers={["المتجر","العنوان","نشط","استقبال الطلبات"]}>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.address_text}</td><td>{r.is_active?"نعم":"لا"}</td><td>{r.is_accepting_orders?"نعم":"متوقف"}</td></tr>)}</Table>}
function Settlements({rows}:{rows:Settlement[]}){return <Table headers={["الفترة","الإجمالي","العمولة","المسترجعات","الصافي","الحالة"]}>{rows.map(r=><tr key={r.id}><td>{r.period_start} → {r.period_end}</td><td>{money(r.gross_amount_minor)}</td><td>{money(r.commission_minor)}</td><td>{money(r.refund_minor)}</td><td><b>{money(r.net_amount_minor)}</b></td><td><span className="badge">{r.status}</span></td></tr>)}</Table>}
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
export default App;
