import {useEffect,useState,type FormEvent,type ReactNode} from "react";
import {getDashboard,updateSubOrderStatus,type Dashboard,type Product,type Settlement,type Store,type SubOrder} from "./lib/api";
import {session,signIn,signOut,supabase} from "./lib/auth";
function money(v:number|string){return (Number(v)/100).toLocaleString("fr-MA",{minimumFractionDigits:2,maximumFractionDigits:2})+" MAD"}
function Login({done}:{done:()=>void}){const[e,setE]=useState("");const[p,setP]=useState("");const[busy,setBusy]=useState(false);const[err,setErr]=useState("");async function submit(x:FormEvent){x.preventDefault();setBusy(true);setErr("");const r=await signIn(e.trim(),p);if(r.error)setErr(r.error);else done();setBusy(false)}return <main className="login"><form onSubmit={submit}><div className="logo">W</div><span className="kicker">WASSLHA MERCHANT</span><h1>لوحة التاجر</h1><p>إدارة المتجر والطلبات والمنتجات والأرباح من مكان واحد.</p><label>Email<input type="email" value={e} onChange={x=>setE(x.target.value)} required/></label><label>Password<input type="password" value={p} onChange={x=>setP(x.target.value)} required/></label>{err&&<div className="error">{err}</div>}<button disabled={busy}>{busy?"جارِ الدخول...":"دخول"}</button></form></main>}
function App(){const[sessionReady,setSessionReady]=useState(false);const[authorized,setAuthorized]=useState(false);const[data,setData]=useState<Dashboard|null>(null);const[token,setToken]=useState("");const[busyOrder,setBusyOrder]=useState<string|null>(null);const[tab,setTab]=useState("overview");const[err,setErr]=useState("");
useEffect(()=>{void (async()=>{const s=await session();setSessionReady(true);if(!s)return;try{setToken(s.access_token);setData(await getDashboard(s.access_token));setAuthorized(true)}catch(e){setErr(e instanceof Error?e.message:"Merchant access denied.")}})()},[]);
async function load(){const s=await session();if(!s)return;try{setToken(s.access_token);setData(await getDashboard(s.access_token));setAuthorized(true);setErr("")}catch(e){setErr(e instanceof Error?e.message:"Unable to load dashboard.")}}
if(!sessionReady)return <main className="login"><div className="loading">جارِ التحقق...</div></main>;
if(!authorized)return <Login done={load}/>;
if(!data)return <main className="login"><div className="error">{err||"Merchant account not found."}</div></main>;
const pending=data.orders.filter(o=>["pending","confirmed","preparing"].includes(o.status)).length;
const revenue=data.settlements.reduce((n,s)=>n+Number(s.net_amount_minor),0);
return <div className="shell"><aside><div className="brand"><span className="logo">W</span><div><b>WASSLHA</b><small>Merchant</small></div></div><nav>{[["overview","الرئيسية"],["orders","الطلبات"],["products","المنتجات"],["stores","المتاجر"],["earnings","الأرباح"]].map(([k,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav><button className="logout" onClick={async()=>{await signOut();location.reload()}}>خروج</button></aside><main className="content"><header><div><span className="kicker">MERCHANT CONTROL CENTER</span><h1>{tab==="overview"?"نظرة عامة":tab==="orders"?"الطلبات":tab==="products"?"المنتجات":tab==="stores"?"المتاجر":"الأرباح"}</h1></div><button className="refresh" onClick={load}>تحديث</button></header>{err&&<div className="error">{err}</div>}{tab==="overview"&&<><section className="cards"><article><span>الطلبات النشيطة</span><b>{pending}</b><small>من آخر 100 طلب</small></article><article><span>المنتجات</span><b>{data.products.length}</b><small>الحالة الحالية</small></article><article><span>المتاجر</span><b>{data.stores.length}</b><small>{data.stores.filter(s=>s.is_active).length} نشطة</small></article><article><span>صافي التسويات</span><b>{money(revenue)}</b><small>حسب settlement records</small></article></section><section className="panel"><h2>آخر الطلبات</h2><Orders rows={data.orders.slice(0,8)} busyOrder={busyOrder} onStatus={async(id,status)=>{setBusyOrder(id);try{await updateSubOrderStatus(token,id,status);await load()}catch(e){setErr(e instanceof Error?e.message:"Unable to update order.")}finally{setBusyOrder(null)}}}/></section></>}{tab==="orders"&&<section className="panel"><h2>طلبات المتجر</h2><Orders rows={data.orders} busyOrder={busyOrder} onStatus={async(id,status)=>{setBusyOrder(id);try{await updateSubOrderStatus(token,id,status);await load()}catch(e){setErr(e instanceof Error?e.message:"Unable to update order.")}finally{setBusyOrder(null)}}}/></section>}{tab==="products"&&<section className="panel"><h2>المنتجات</h2><Products rows={data.products}/></section>}{tab==="stores"&&<section className="panel"><h2>المتاجر</h2><Stores rows={data.stores}/></section>}{tab==="earnings"&&<section className="panel"><h2>التسويات المالية</h2><Settlements rows={data.settlements}/></section>}</main></div>}
function Orders({rows,busyOrder,onStatus}:{rows:SubOrder[];busyOrder:string|null;onStatus:(id:string,status:string)=>Promise<void>}){return <Table headers={["الطلب","الحالة","المجموع","التاريخ","الإجراء"]}>{rows.map(r=><tr key={r.id}><td><b>{r.sub_order_number}</b></td><td><span className="badge">{r.status}</span></td><td>{money(r.total_minor)}</td><td>{new Date(r.created_at).toLocaleString("fr-MA")}</td><td><OrderActions row={r} busy={busyOrder===r.id} onStatus={onStatus}/></td></tr>)}</Table>}
function OrderActions({row,busy,onStatus}:{row:SubOrder;busy:boolean;onStatus:(id:string,status:string)=>Promise<void>}){const next=row.status==="pending"?["confirmed","cancelled"]:row.status==="confirmed"?["preparing","cancelled"]:row.status==="preparing"?["ready_for_pickup","cancelled"]:[];return next.length?<div className="actions">{next.map(s=><button key={s} disabled={busy} onClick={()=>onStatus(row.id,s)}>{busy?"...":s}</button>)}</div>:<span>—</span>}
function Products({rows}:{rows:Product[]}){return <Table headers={["المنتج","السعر","المخزون","الظهور","الموافقة"]}>{rows.map(r=><tr key={r.id}><td><b>{r.name_ar}</b><small>{r.name_fr}</small></td><td>{money(r.price_minor)}</td><td>{r.stock_quantity} {r.stock_unit}</td><td>{r.is_active&&r.is_available?"متاح":"غير متاح"}</td><td><span className="badge">{r.approval_status}</span></td></tr>)}</Table>}
function Stores({rows}:{rows:Store[]}){return <Table headers={["المتجر","العنوان","نشط","استقبال الطلبات"]}>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b></td><td>{r.address_text}</td><td>{r.is_active?"نعم":"لا"}</td><td>{r.is_accepting_orders?"نعم":"متوقف"}</td></tr>)}</Table>}
function Settlements({rows}:{rows:Settlement[]}){return <Table headers={["الفترة","الإجمالي","العمولة","المسترجعات","الصافي","الحالة"]}>{rows.map(r=><tr key={r.id}><td>{r.period_start} → {r.period_end}</td><td>{money(r.gross_amount_minor)}</td><td>{money(r.commission_minor)}</td><td>{money(r.refund_minor)}</td><td><b>{money(r.net_amount_minor)}</b></td><td><span className="badge">{r.status}</span></td></tr>)}</Table>}
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
export default App;
