import { databaseGet, type DatabaseEnv } from "../lib/database";
import { servicePost, servicePatch, type ServiceAuthEnv } from "../lib/service-client";
export interface CommunicationServiceEnv extends DatabaseEnv, ServiceAuthEnv {}
export interface Conversation{id:string;conversation_type:string;master_order_id?:string|null;created_by?:string|null;status:string;created_at:string;updated_at:string}
export interface Message{id:string;conversation_id:string;sender_id:string;message_type:string;body?:string|null;metadata:Record<string,unknown>;read_at?:string|null;created_at:string}
export interface CallSession{id:string;conversation_id?:string|null;caller_id:string;callee_id:string;provider?:string|null;provider_call_id?:string|null;status:string;started_at?:string|null;ended_at?:string|null;created_at:string}
export interface NotificationPreference{id:string;user_id:string;push_enabled:boolean;sms_enabled:boolean;telegram_enabled:boolean;order_updates:boolean;promotions:boolean;support_updates:boolean}
export interface CommunicationResult<T>{success:boolean;data:T|null;error:string|null}
export async function getConversations(userId:string,env:CommunicationServiceEnv,token:string){const r=await databaseGet<Conversation[]>("/rest/v1/conversations?select=*&created_by=eq."+encodeURIComponent(userId)+"&order=updated_at.desc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as CommunicationResult<Conversation[]>}
export async function getMessages(conversationId:string,env:CommunicationServiceEnv,token:string){const r=await databaseGet<Message[]>("/rest/v1/messages?select=*&conversation_id=eq."+encodeURIComponent(conversationId)+"&order=created_at.asc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as CommunicationResult<Message[]>}
export async function createConversation(body:{conversation_type:"order"|"support"|"direct";master_order_id?:string|null;created_by:string},env:CommunicationServiceEnv){const r=await servicePost<Conversation[]>("/rest/v1/conversations",env,{...body,status:"active"});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as CommunicationResult<Conversation|null>}
export async function sendMessage(body:{conversation_id:string;sender_id:string;message_type?:"text"|"image"|"file"|"system";body?:string|null;metadata?:Record<string,unknown>},env:CommunicationServiceEnv){const r=await servicePost<Message[]>("/rest/v1/messages",env,{...body,message_type:body.message_type??"text",metadata:body.metadata??{}});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as CommunicationResult<Message|null>}
export async function markMessageRead(messageId:string,env:CommunicationServiceEnv){const r=await servicePatch<Message[]>("/rest/v1/messages?id=eq."+encodeURIComponent(messageId),env,{read_at:new Date().toISOString()});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as CommunicationResult<Message|null>}
export async function getNotificationPreferences(userId:string,env:CommunicationServiceEnv,token:string){const r=await databaseGet<NotificationPreference[]>("/rest/v1/notification_preferences?select=*&user_id=eq."+encodeURIComponent(userId)+"&limit=1",env,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as CommunicationResult<NotificationPreference|null>}
