import { databaseGet, type DatabaseEnv } from "../lib/database";
import { servicePost, servicePatch, type ServiceAuthEnv } from "../lib/service-client";
export interface GetRequestServiceEnv extends DatabaseEnv, ServiceAuthEnv {}
export interface GetRequest{id:string;customer_id:string;address_id?:string|null;master_order_id?:string|null;request_title:string;request_description?:string|null;pickup_place_name?:string|null;pickup_place_address?:string|null;pickup_latitude?:number|null;pickup_longitude?:number|null;delivery_address_text?:string|null;delivery_latitude?:number|null;delivery_longitude?:number|null;estimated_product_amount_minor?:string|null;maximum_product_amount_minor?:string|null;delivery_fee_minor?:string|null;service_fee_minor?:string|null;total_estimated_amount_minor?:string|null;currency:"MAD";status:string;expires_at?:string|null;accepted_at?:string|null;completed_at?:string|null;cancelled_at?:string|null;cancellation_reason?:string|null;idempotency_key:string;metadata:Record<string,unknown>;created_at:string;updated_at:string}
export interface GetRequestItem{id:string;get_request_id:string;item_name:string;description?:string|null;quantity:number;unit?:string|null;estimated_unit_price_minor?:string|null;maximum_unit_price_minor?:string|null;notes?:string|null;created_at:string}
export interface GetRequestOffer{id:string;get_request_id:string;rider_id?:string|null;offered_product_amount_minor?:string|null;offered_delivery_fee_minor?:string|null;offered_service_fee_minor?:string|null;offered_total_amount_minor?:string|null;currency:"MAD";status:string;message?:string|null;expires_at?:string|null;accepted_at?:string|null;created_at:string;updated_at:string}
export interface GetRequestResult<T>{success:boolean;data:T|null;error:string|null}
export async function getMyRequests(customerId:string,env:GetRequestServiceEnv,token:string){const r=await databaseGet<GetRequest[]>("/rest/v1/get_requests?select=*&customer_id=eq."+encodeURIComponent(customerId)+"&order=created_at.desc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as GetRequestResult<GetRequest[]>}
export async function getRequest(id:string,env:GetRequestServiceEnv,token:string){const r=await databaseGet<GetRequest[]>("/rest/v1/get_requests?select=*&id=eq."+encodeURIComponent(id)+"&limit=1",env,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as GetRequestResult<GetRequest|null>}
export async function getRequestItems(id:string,env:GetRequestServiceEnv,token:string){const r=await databaseGet<GetRequestItem[]>("/rest/v1/get_request_items?select=*&get_request_id=eq."+encodeURIComponent(id)+"&order=created_at.asc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as GetRequestResult<GetRequestItem[]>}
export async function getRequestOffers(id:string,env:GetRequestServiceEnv,token:string){const r=await databaseGet<GetRequestOffer[]>("/rest/v1/get_request_offers?select=*&get_request_id=eq."+encodeURIComponent(id)+"&order=created_at.desc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as GetRequestResult<GetRequestOffer[]>}
export async function createGetRequest(body:{customer_id:string;request_title:string;request_description?:string|null;pickup_place_name?:string|null;pickup_place_address?:string|null;delivery_address_text?:string|null;delivery_latitude?:number|null;delivery_longitude?:number|null;idempotency_key:string},env:GetRequestServiceEnv){const r=await servicePost<GetRequest[]>("/rest/v1/get_requests",env,{...body,currency:"MAD",status:"pending"});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as GetRequestResult<GetRequest|null>}
export async function addRequestItem(body:{get_request_id:string;item_name:string;description?:string|null;quantity:number;unit?:string|null;estimated_unit_price_minor?:string|null;maximum_unit_price_minor?:string|null;notes?:string|null},env:GetRequestServiceEnv){const r=await servicePost<GetRequestItem[]>("/rest/v1/get_request_items",env,body);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as GetRequestResult<GetRequestItem|null>}
export async function createOffer(body:{get_request_id:string;rider_id?:string|null;offered_product_amount_minor?:string|null;offered_delivery_fee_minor?:string|null;offered_service_fee_minor?:string|null;offered_total_amount_minor?:string|null;message?:string|null;expires_at?:string|null},env:GetRequestServiceEnv){const r=await servicePost<GetRequestOffer[]>("/rest/v1/get_request_offers",env,{...body,currency:"MAD",status:"pending"});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as GetRequestResult<GetRequestOffer|null>}
export async function updateRequestStatus(id:string,status:string,env:GetRequestServiceEnv){const r=await servicePatch<GetRequest[]>("/rest/v1/get_requests?id=eq."+encodeURIComponent(id),env,{status});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as GetRequestResult<GetRequest|null>}
