import { databaseGet, type DatabaseEnv } from "../lib/database";
import { servicePost, type ServiceAuthEnv } from "../lib/service-client";

export interface GrowthServiceEnv extends DatabaseEnv, ServiceAuthEnv {}
export interface Promotion { id:string; name:string; description?:string|null; promotion_type:string; discount_percent?:number|null; discount_amount_minor?:string|null; minimum_order_amount_minor?:string|null; maximum_discount_amount_minor?:string|null; usage_limit?:number|null; usage_limit_per_user?:number|null; starts_at:string; ends_at:string; is_active:boolean; conditions:Record<string,unknown>; }
export interface PromoCode { id:string; promotion_id:string; code:string; is_active:boolean; usage_limit?:number|null; usage_count:number; }
export interface LoyaltyAccount { id:string; user_id:string; points_balance:string; lifetime_earned_points:string; lifetime_redeemed_points:string; status:string; }
export interface LoyaltyTransaction { id:string; loyalty_account_id:string; transaction_type:string; points:number; balance_before:string; balance_after:string; reference_type?:string|null; reference_id?:string|null; idempotency_key:string; description?:string|null; metadata:Record<string,unknown>; created_at:string; }
export interface Referral { id:string; referrer_id:string; referred_user_id:string; referral_code:string; status:string; reward_amount_minor?:string|null; reward_currency:"MAD"; qualified_order_id?:string|null; rewarded_at?:string|null; idempotency_key:string; }
export interface GrowthResult<T>{success:boolean;data:T|null;error:string|null}
export async function getActivePromotions(env:GrowthServiceEnv,token:string){const r=await databaseGet<Promotion[]>("/rest/v1/promotions?select=*&is_active=eq.true&order=starts_at.asc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as GrowthResult<Promotion[]>}
export async function getPromoCode(code:string,env:GrowthServiceEnv,token:string){const r=await databaseGet<PromoCode[]>("/rest/v1/promo_codes?select=*&code=ilike."+encodeURIComponent(code)+"&is_active=eq.true&limit=1",env,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as GrowthResult<PromoCode|null>}
export async function getLoyaltyAccount(userId:string,env:GrowthServiceEnv,token:string){const r=await databaseGet<LoyaltyAccount[]>("/rest/v1/loyalty_accounts?select=*&user_id=eq."+encodeURIComponent(userId)+"&limit=1",env,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as GrowthResult<LoyaltyAccount|null>}
export async function getLoyaltyTransactions(accountId:string,env:GrowthServiceEnv,token:string){const r=await databaseGet<LoyaltyTransaction[]>("/rest/v1/loyalty_transactions?select=*&loyalty_account_id=eq."+encodeURIComponent(accountId)+"&order=created_at.desc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as GrowthResult<LoyaltyTransaction[]>}
export async function getUserReferrals(userId:string,env:GrowthServiceEnv,token:string){const r=await databaseGet<Referral[]>("/rest/v1/referrals?select=*&or=(referrer_id.eq."+encodeURIComponent(userId)+",referred_user_id.eq."+encodeURIComponent(userId)+")&order=created_at.desc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as GrowthResult<Referral[]>}
export async function createPromoRedemption(body:{promotion_id:string;promo_code_id?:string|null;user_id:string;master_order_id:string;discount_amount_minor:string;idempotency_key:string},env:GrowthServiceEnv){const r=await servicePost<Array<{id:string}>>("/rest/v1/promo_redemptions",env,{...body,currency:"MAD"});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as GrowthResult<{id:string}|null>}
