import { databaseGet,databaseInsert,databaseUpdate,type DatabaseEnv } from "../lib/database";
export interface ProductServiceEnv extends DatabaseEnv {}
export interface Product{id:string;store_id:string;category_id?:string|null;name_ar:string;name_fr:string;description_ar?:string|null;description_fr?:string|null;sku?:string|null;price_minor:number;compare_at_price_minor?:number|null;currency:"MAD";stock_quantity:number;stock_unit:string;is_available:boolean;is_active:boolean;approval_status:string;rejection_reason?:string|null;created_at?:string;updated_at?:string}
export interface PublicProduct{id:string;store_id:string;category_id?:string|null;name_ar:string;name_fr:string;description_ar?:string|null;description_fr?:string|null;price_minor:number;compare_at_price_minor?:number|null;currency:"MAD";stock_unit:string;is_available:boolean}
export interface ProductServiceResult<T>{success:boolean;data:T|null;error:string|null}
export async function getStoreProducts(id:string,env:ProductServiceEnv,token:string){const r=await databaseGet<Product[]>(`/rest/v1/products?select=*&store_id=eq.${encodeURIComponent(id)}&order=created_at.desc`,env,token);return {success:!r.error,data:r.data??[],error:r.error} as ProductServiceResult<Product[]>}
export async function getProduct(id:string,env:ProductServiceEnv,token:string){const r=await databaseGet<Product[]>(`/rest/v1/products?select=*&id=eq.${encodeURIComponent(id)}&limit=1`,env,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as ProductServiceResult<Product|null>}
export async function getPublicProduct(id:string,env:ProductServiceEnv,token?:string){const r=await databaseGet<PublicProduct[]>(`/rest/v1/products?select=id,store_id,category_id,name_ar,name_fr,description_ar,description_fr,price_minor,compare_at_price_minor,currency,stock_unit,is_available&id=eq.${encodeURIComponent(id)}&is_active=eq.true&approval_status=eq.approved&is_available=eq.true&limit=1`,env,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as ProductServiceResult<PublicProduct|null>}
export async function createProduct(storeId:string,env:ProductServiceEnv,token:string,product:Omit<Product,"id"|"store_id"|"created_at"|"updated_at">){const r=await databaseInsert<Product[]>("/rest/v1/products",env,{...product,store_id:storeId},token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as ProductServiceResult<Product|null>}
export async function updateProduct(id:string,storeId:string,env:ProductServiceEnv,token:string,updates:Partial<Pick<Product,"category_id"|"name_ar"|"name_fr"|"description_ar"|"description_fr"|"sku"|"price_minor"|"compare_at_price_minor"|"stock_quantity"|"stock_unit"|"is_available"|"is_active">>){const r=await databaseUpdate<Product[]>(`/rest/v1/products?id=eq.${encodeURIComponent(id)}&store_id=eq.${encodeURIComponent(storeId)}`,env,updates,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as ProductServiceResult<Product|null>}
