import { databaseGet,databaseInsert,databaseUpdate,type DatabaseEnv } from "../lib/database";
export interface StoreServiceEnv extends DatabaseEnv {}
export interface Store{id:string;merchant_id:string;name:string;description?:string|null;phone?:string|null;address_text:string;latitude?:number|null;longitude?:number|null;is_active:boolean;is_accepting_orders:boolean;opening_hours?:Record<string,{open:string;close:string}|null>|null;orders_paused?:boolean;orders_pause_reason?:string|null;created_at?:string;updated_at?:string}
export interface PublicStore{id:string;name:string;description?:string|null;phone?:string|null;address_text:string;latitude?:number|null;longitude?:number|null;is_active:boolean;is_accepting_orders:boolean;opening_hours?:Record<string,{open:string;close:string}|null>|null;orders_paused?:boolean}
export interface StoreServiceResult<T>{success:boolean;data:T|null;error:string|null}
export async function getMerchantStores(id:string,env:StoreServiceEnv,token:string){const r=await databaseGet<Store[]>(`/rest/v1/stores?select=*&merchant_id=eq.${encodeURIComponent(id)}&order=created_at.desc`,env,token);return {success:!r.error,data:r.data??[],error:r.error} as StoreServiceResult<Store[]>}
export async function getStore(id:string,env:StoreServiceEnv,token:string){const r=await databaseGet<Store[]>(`/rest/v1/stores?select=*&id=eq.${encodeURIComponent(id)}&limit=1`,env,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as StoreServiceResult<Store|null>}
export async function getPublicStore(id:string,env:StoreServiceEnv,token?:string){const r=await databaseGet<PublicStore[]>(`/rest/v1/stores?select=id,name,description,phone,address_text,latitude,longitude,is_active,is_accepting_orders,opening_hours,orders_paused&id=eq.${encodeURIComponent(id)}&is_active=eq.true&limit=1`,env,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as StoreServiceResult<PublicStore|null>}
export async function createStore(merchantId:string,env:StoreServiceEnv,token:string,store:Omit<Store,"id"|"merchant_id"|"created_at"|"updated_at">){const r=await databaseInsert<Store[]>("/rest/v1/stores",env,{...store,merchant_id:merchantId},token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as StoreServiceResult<Store|null>}
export async function updateStore(id:string,merchantId:string,env:StoreServiceEnv,token:string,updates:Partial<Pick<Store,"name"|"description"|"phone"|"address_text"|"latitude"|"longitude"|"is_active"|"is_accepting_orders"|"opening_hours"|"orders_paused"|"orders_pause_reason">>){const r=await databaseUpdate<Store[]>(`/rest/v1/stores?id=eq.${encodeURIComponent(id)}&merchant_id=eq.${encodeURIComponent(merchantId)}`,env,updates,token);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as StoreServiceResult<Store|null>}
