import { databaseGet, type DatabaseEnv } from "../lib/database";
import { servicePost, servicePatch, type ServiceAuthEnv } from "../lib/service-client";
export interface SupportServiceEnv extends DatabaseEnv, ServiceAuthEnv {}
export interface SupportTicket{id:string;user_id:string;master_order_id?:string|null;subject:string;description:string;category:string;priority:string;status:string;assigned_to?:string|null;resolved_at?:string|null;created_at:string;updated_at:string}
export interface Complaint{id:string;user_id:string;master_order_id?:string|null;complaint_type:string;description:string;status:string;resolution?:string|null;resolved_by?:string|null;resolved_at?:string|null;created_at:string;updated_at:string}
export interface Review{id:string;user_id:string;master_order_id:string;merchant_id?:string|null;rider_id?:string|null;rating:number;title?:string|null;body?:string|null;is_published:boolean;created_at:string;updated_at:string}
export interface ReviewReply{id:string;review_id:string;user_id:string;body:string;created_at:string;updated_at:string}
export interface SupportResult<T>{success:boolean;data:T|null;error:string|null}
export async function getMyTickets(userId:string,env:SupportServiceEnv,token:string){const r=await databaseGet<SupportTicket[]>("/rest/v1/support_tickets?select=*&user_id=eq."+encodeURIComponent(userId)+"&order=created_at.desc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as SupportResult<SupportTicket[]>}
export async function getMyComplaints(userId:string,env:SupportServiceEnv,token:string){const r=await databaseGet<Complaint[]>("/rest/v1/complaints?select=*&user_id=eq."+encodeURIComponent(userId)+"&order=created_at.desc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as SupportResult<Complaint[]>}
export async function getPublishedReviews(env:SupportServiceEnv,token:string,merchantId?:string){const filter=merchantId?"&merchant_id=eq."+encodeURIComponent(merchantId):"";const r=await databaseGet<Review[]>("/rest/v1/reviews?select=*&is_published=eq.true"+filter+"&order=created_at.desc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as SupportResult<Review[]>}
export async function getReviewReplies(reviewId:string,env:SupportServiceEnv,token:string){const r=await databaseGet<ReviewReply[]>("/rest/v1/review_replies?select=*&review_id=eq."+encodeURIComponent(reviewId)+"&order=created_at.asc",env,token);return {success:!r.error,data:r.data??[],error:r.error} as SupportResult<ReviewReply[]>}
export async function createSupportTicket(body:{user_id:string;master_order_id?:string|null;subject:string;description:string;category:string;priority?:string},env:SupportServiceEnv){const r=await servicePost<SupportTicket[]>("/rest/v1/support_tickets",env,{...body,priority:body.priority??"normal",status:"open"});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as SupportResult<SupportTicket|null>}
export async function createComplaint(body:{user_id:string;master_order_id?:string|null;complaint_type:string;description:string},env:SupportServiceEnv){const r=await servicePost<Complaint[]>("/rest/v1/complaints",env,{...body,status:"open"});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as SupportResult<Complaint|null>}
export async function createReview(body:{user_id:string;master_order_id:string;merchant_id?:string|null;rider_id?:string|null;rating:number;title?:string|null;body?:string|null},env:SupportServiceEnv){if(body.rating<1||body.rating>5)return {success:false,data:null,error:"Rating must be between 1 and 5"} as SupportResult<Review|null>;const r=await servicePost<Review[]>("/rest/v1/reviews",env,{...body,is_published:true});return {success:!r.error,data:r.data?.[0]??null,error:r.error} as SupportResult<Review|null>}
export async function replyToReview(body:{review_id:string;user_id:string;body:string},env:SupportServiceEnv){const r=await servicePost<ReviewReply[]>("/rest/v1/review_replies",env,body);return {success:!r.error,data:r.data?.[0]??null,error:r.error} as SupportResult<ReviewReply|null>}
