import { useEffect, useMemo, useState } from "react";
import * as Location from "expo-location";
import { Alert, ActivityIndicator, Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import type { Session } from "@supabase/supabase-js";
import { supabase, supabaseConfigured } from "./src/lib/supabase";

const API=(process.env.EXPO_PUBLIC_API_BASE_URL??"").replace(/\/$/,"");
const ONLINE_PAYMENTS_ENABLED=process.env.EXPO_PUBLIC_ONLINE_PAYMENTS_ENABLED==="true";
const idempotencyKey=()=>Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,14);
type Variant={id:string;name_ar:string;name_fr:string;price_minor:number;stock_quantity:number;is_available:boolean};
type Product={id:string;store_id:string;name_ar:string;name_fr:string;description_ar?:string|null;description_fr?:string|null;price_minor:number;is_available:boolean;store_name?:string|null;variants?:Variant[]};
type Store={id:string;name:string;address_text:string;is_accepting_orders:boolean};
type Category={id:string;name_ar:string;name_fr:string};
type Address={id:string;label?:string|null;address_text:string;latitude:number;longitude:number;is_default:boolean};
type Delivery={id:string;status:string|null;eta_seconds:number|null;delivery_address_text:string;delivery_latitude:number|null;delivery_longitude:number|null};
type Order={id:string;order_number?:string;master_order_number?:string;status:string;total_minor?:number;payment_method?:string;payment_status?:string;created_at:string;deliveries?:Delivery[]};
type Request={id:string;request_title:string;status:string;created_at:string};
type Cart={product:Product;quantity:number;variant?:Variant};
type Quote={subtotal_minor:number;delivery_fee_minor:number;service_fee_minor:number;discount_minor:number;tip_minor:number;total_minor:number;distance_meters:number;eta_seconds:number;currency:"MAD";route_count:number};

async function api<T>(path:string,session:Session,options:RequestInit={}):Promise<T>{const headers={Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{}),Authorization:`Bearer ${session.access_token}`,...(options.headers??{})};const r=await fetch(`${API}/api/v1/${path}`,{...options,headers});const p=await r.json() as {success?:boolean;data?:T;error?:{message?:string}};if(!r.ok||!p.success)throw new Error(p.error?.message??"تعذر الاتصال بالخدمة");return p.data as T}
const money=(n:number)=>`${(n/100).toFixed(2)} DH`;
const orderStatusLabel=(v:string)=>({pending:"في انتظار التأكيد",confirmed:"مؤكد",preparing:"كيجهز",assigned:"سائق تعيّن",picked_up:"تم الاستلام",out_for_delivery:"في الطريق",delivered:"تم التوصيل",cancelled:"ملغى",failed:"تعذر التوصيل"} as Record<string,string>)[v]??v;
const awaitingPayment=(o:Order)=>o.payment_method==="online"&&o.payment_status!=="paid"&&o.status==="pending";
const deliveryStatusLabel=(v:string|null|undefined)=>({pending:"في الانتظار",assigned:"سائق تعيّن",accepted:"السائق قبل",at_pickup:"وصل للمتجر",picked_up:"استلم الطلب",in_transit:"في الطريق",delivered:"تم التوصيل",failed:"تعذر التوصيل",cancelled:"ملغى"} as Record<string,string>)[v??""]??v??"—";
const phone=(v:string)=>{const x=v.replace(/\s/g,"");return /^0[67]\d{8}$/.test(x)?`+212${x.slice(1)}`:x};
function Btn({title,onPress,light=false,disabled=false}:{title:string;onPress:()=>void;light?:boolean;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.btn,light&&s.btnLight,disabled&&s.disabled]}><Text style={[s.btnText,light&&s.btnLightText]}>{title}</Text></Pressable>}

function Auth({onDone}:{onDone:(s:Session)=>void}){const[p,setP]=useState("");const[c,setC]=useState("");const[sent,setSent]=useState(false);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");async function send(){setBusy(true);const r=await supabase.auth.signInWithOtp({phone:phone(p)});setErr(r.error?.message??"");if(!r.error)setSent(true);setBusy(false)}async function verify(){setBusy(true);const r=await supabase.auth.verifyOtp({phone:phone(p),token:c.trim(),type:"sms"});setErr(r.error?.message??"");if(r.data.session)onDone(r.data.session);setBusy(false)}return <SafeAreaView style={s.safe}><View style={s.auth}><Text style={s.logo}>W</Text><Text style={s.brand}>WASSLHA</Text><Text style={s.muted}>برشيد • توصيل محلي</Text><Text style={s.h1}>{sent?"دخل كود SMS":"مرحبا بك"}</Text><TextInput keyboardType={sent?"number-pad":"phone-pad"} placeholder={sent?"123456":"06 00 00 00 00"} value={sent?c:p} onChangeText={sent?setC:setP} style={s.input}/>{err?<Text style={s.err}>{err}</Text>:null}<Btn title={busy?"...":sent?"تأكيد":"إرسال الكود"} onPress={()=>void(sent?verify():send())} disabled={busy||(sent?c.length<4:p.length<9)}/></View></SafeAreaView>}

export default function App(){const[session,setSession]=useState<Session|null>(null);const[ready,setReady]=useState(false);useEffect(()=>{let m=true;(async()=>{if(!supabaseConfigured||!API){setReady(true);return}const r=await supabase.auth.getSession();if(m){setSession(r.data.session);setReady(true)}})();const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,x)=>setSession(x));return()=>{m=false;subscription.unsubscribe()}},[]);if(!ready)return <SafeAreaView style={s.safe}><ActivityIndicator style={{marginTop:80}}/></SafeAreaView>;if(!supabaseConfigured||!API)return <SafeAreaView style={s.safe}><Text style={s.err}>خص إعداد Supabase و API URL.</Text></SafeAreaView>;return session?<Home session={session}/>:<Auth onDone={setSession}/>}

function Home({session}:{session:Session}){const[tab,setTab]=useState<"home"|"search"|"orders"|"cart"|"profile">("home");const[cats,setCats]=useState<Category[]>([]);const[stores,setStores]=useState<Store[]>([]);const[products,setProducts]=useState<Product[]>([]);const[addresses,setAddresses]=useState<Address[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[requests,setRequests]=useState<Request[]>([]);const[cart,setCart]=useState<Cart[]>([]);const[q,setQ]=useState("");const[cat,setCat]=useState<string|null>(null);const[address,setAddress]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[err,setErr]=useState("");const[quote,setQuote]=useState<Quote|null>(null);const[tip,setTip]=useState(0);const[paymentMethod,setPaymentMethod]=useState<"cod"|"online">("cod");const[getMode,setGetMode]=useState(false);const[getTitle,setGetTitle]=useState("");const[getPlace,setGetPlace]=useState("");const[getItem,setGetItem]=useState("");const subtotal=useMemo(()=>cart.reduce((x,i)=>x+i.product.price_minor*i.quantity,0),[cart]);const[tracking,setTracking]=useState<Record<string,{latitude:number;longitude:number;recorded_at:string;status:string;eta_seconds:number|null;distance_meters:number|null}>>({});
 async function load(){try{const[c,st,p,a,o,r]=await Promise.all([api<Category[]>("categories",session),api<Store[]>("catalog/stores?limit=30",session),api<Product[]>("catalog/products?limit=60",session),api<Address[]>("customer/me/addresses",session),api<Order[]>("customer/me/orders",session),api<Request[]>("get-requests",session)]);setCats(c);setStores(st);setProducts(p);setAddresses(a);setOrders(o);setRequests(r);if(!address&&a.length)setAddress(a.find(x=>x.is_default)?.id??a[0].id)}catch(e){setErr(e instanceof Error?e.message:"تعذر التحميل")}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{let dead=false;const timer=setTimeout(async()=>{if(!cart.length||!address){setQuote(null);return}try{const q=await api<Quote>("orders/quote",session,{method:"POST",body:JSON.stringify({delivery_address_id:address,items:cart.map(i=>({product_id:i.product.id,variant_id:i.variant?.id,quantity:i.quantity})),tip_minor:tip})});if(!dead)setQuote(q)}catch{if(!dead)setQuote(null)}},250);return()=>{dead=true;clearTimeout(timer)}},[cart,address,tip,session]);
 useEffect(()=>{const active=orders.flatMap(o=>o.deliveries??[]).filter(d=>["assigned","accepted","at_pickup","picked_up","in_transit"].includes(d.status??""));if(!active.length)return;let dead=false;async function refresh(){for(const d of active){try{const p=await api<{delivery:{status:string;eta_seconds:number|null;distance_meters:number|null};location:{latitude:number;longitude:number;recorded_at:string}|null}>(`customer/me/deliveries/${d.id}`,session);if(!dead&&p)setTracking(v=>({...v,[d.id]:p.location?{...p.location,status:p.delivery.status,eta_seconds:p.delivery.eta_seconds,distance_meters:p.delivery.distance_meters}:{latitude:0,longitude:0,recorded_at:"",status:p.delivery.status,eta_seconds:p.delivery.eta_seconds,distance_meters:p.delivery.distance_meters}}))}catch{}}}void refresh();const t=setInterval(()=>void refresh(),10000);return()=>{dead=true;clearInterval(t)}},[orders,session]);

 async function search(){setBusy(true);try{const p=new URLSearchParams({limit:"60"});if(q.trim())p.set("q",q.trim());if(cat)p.set("category_id",cat);setProducts(await api<Product[]>(`catalog/products?${p}`,session))}catch(e){setErr(e instanceof Error?e.message:"تعذر البحث")}finally{setBusy(false)}}
 function add(product:Product,variant?:Variant){if(!product.is_available)return;if(product.variants?.length&&!variant){Alert.alert("اختيار المنتج","اختار الحجم أو الاختيار أولاً.");return}const key=product.id+":"+(variant?.id??"base");setCart(x=>{const f=x.find(i=>i.product.id+":"+(i.variant?.id??"base")===key);return f?x.map(i=>i.product.id+":"+(i.variant?.id??"base")===key?{...i,quantity:i.quantity+1}:i):[...x,{product,variant,quantity:1}]})}
 function qty(id:string,d:number){setCart(x=>x.flatMap(i=>i.product.id===id?(i.quantity+d>0?[{...i,quantity:i.quantity+d}]:[]):[i]))}
 async function locate(){const p=await Location.requestForegroundPermissionsAsync();if(p.status!=="granted")return Alert.alert("الموقع","سمح بالموقع أولاً");const x=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setBusy(true);try{const a=await api<Address>("customer/me/addresses",session,{method:"POST",body:JSON.stringify({label:"موقعي",address_text:`GPS ${x.coords.latitude.toFixed(5)}, ${x.coords.longitude.toFixed(5)}`,latitude:x.coords.latitude,longitude:x.coords.longitude,is_default:addresses.length===0})});setAddresses(v=>[a,...v]);setAddress(a.id)}catch(e){Alert.alert("العنوان",e instanceof Error?e.message:"تعذر الحفظ")}finally{setBusy(false)}}
 async function checkout(){if(!address)return Alert.alert("العنوان","اختار عنوان التوصيل");if(!cart.length)return;if(!quote)return Alert.alert("الطلب","جاري حساب رسوم التوصيل، عاود المحاولة بعد لحظة.");const method=ONLINE_PAYMENTS_ENABLED?paymentMethod:"cod";setBusy(true);try{await api("orders",session,{method:"POST",headers:{"Idempotency-Key":idempotencyKey()},body:JSON.stringify({delivery_address_id:address,payment_method:method,tip_minor:tip,items:cart.map(i=>({product_id:i.product.id,quantity:i.quantity}))})});setCart([]);setTab("orders");Alert.alert("تم",method==="online"?"تسجل الطلب. غادي يتأكد ملي يتم الدفع.":"تسجل الطلب بنجاح");await load()}catch(e){Alert.alert("الطلب",e instanceof Error?e.message:"تعذر الطلب")}finally{setBusy(false)}}
 async function requestRefund(orderId:string,amount:number){setBusy(true);try{await api("customer/me/refunds",session,{method:"POST",headers:{"Idempotency-Key":idempotencyKey()},body:JSON.stringify({master_order_id:orderId,amount_minor:String(amount),reason_code:"order_cancelled",reason_text:"Customer requested refund"})});Alert.alert("تم","طلب الاسترجاع تسجل وغادي يراجعو الفريق.");await load()}catch(e){Alert.alert("الاسترجاع",e instanceof Error?e.message:"تعذر طلب الاسترجاع")}finally{setBusy(false)}}
 async function createGet(){if(!address||!getTitle.trim()||!getItem.trim())return Alert.alert("معلومات ناقصة","دخل الطلب واختار العنوان");const a=addresses.find(x=>x.id===address)!;setBusy(true);try{const r=await api<Request>("get-requests",session,{method:"POST",headers:{"Idempotency-Key":idempotencyKey()},body:JSON.stringify({request_title:getTitle.trim(),request_description:getItem.trim(),pickup_place_name:getPlace.trim()||null,delivery_address_text:a.address_text,delivery_latitude:a.latitude,delivery_longitude:a.longitude})});await api(`get-requests/${r.id}/items`,session,{method:"POST",body:JSON.stringify({item_name:getItem.trim(),quantity:1})});setGetMode(false);setTab("orders");setGetTitle("");setGetItem("");setGetPlace("");await load();Alert.alert("تم","طلب جيب ليا تسجل")}catch(e){Alert.alert("جيب ليا",e instanceof Error?e.message:"تعذر الطلب")}finally{setBusy(false)}}
 if(getMode)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.pad}><Pressable onPress={()=>setGetMode(false)}><Text style={s.link}>‹ رجوع</Text></Pressable><Text style={s.h1}>جيب ليا</Text><TextInput placeholder="شنو بغيتي؟" value={getTitle} onChangeText={setGetTitle} style={s.input}/><TextInput placeholder="التفاصيل" value={getItem} onChangeText={setGetItem} multiline style={[s.input,{height:90}]}/><TextInput placeholder="منين؟" value={getPlace} onChangeText={setGetPlace} style={s.input}/><Addresses data={addresses} selected={address} setSelected={setAddress} locate={locate}/><Btn title={busy?"...":"إرسال الطلب"} onPress={()=>void createGet()} disabled={busy}/></ScrollView></SafeAreaView>;
 return <SafeAreaView style={s.safe}><View style={s.head}><View><Text style={s.kicker}>WASSLHA</Text><Text style={s.headTitle}>برشيد</Text></View><Pressable onPress={()=>setTab("cart")}><Text style={s.cart}>🛒 {cart.length||""}</Text></Pressable></View><ScrollView contentContainerStyle={s.pad}>
 {tab==="home"&&<><Pressable style={s.banner} onPress={()=>setGetMode(true)}><Text style={s.bannerTitle}>جيب ليا</Text><Text style={s.bannerText}>ما لقيتيش اللي بغيتي؟ خليه علينا.</Text></Pressable><Text style={s.section}>التصنيفات</Text><ScrollView horizontal>{cats.map(c=><Pressable key={c.id} onPress={()=>{setCat(c.id);setTab("search");void search()}} style={s.chip}><Text>{c.name_ar}</Text></Pressable>)}</ScrollView><Text style={s.section}>المتاجر</Text>{stores.slice(0,8).map(x=><View key={x.id} style={s.card}><Text style={s.title}>{x.name}</Text><Text style={s.muted}>{x.address_text}</Text><Text style={s.muted}>{x.is_accepting_orders?"مفتوح":"مغلق"}</Text></View>)}<Text style={s.section}>المنتجات</Text>{products.slice(0,12).map(p=><Product key={p.id} p={p} add={()=>add(p)}/>)}</>}
 {tab==="search"&&<><Text style={s.h1}>البحث</Text><View style={s.row}><TextInput placeholder="شنو كتقلب عليه؟" value={q} onChangeText={setQ} onSubmitEditing={()=>void search()} style={[s.input,{flex:1}]}/><Btn title="بحث" onPress={()=>void search()}/></View>{products.map(p=><Product key={p.id} p={p} add={()=>add(p)}/>)}</>}
 {tab==="orders"&&<><Text style={s.h1}>طلباتي</Text>{orders.map(o=><OrderCard key={o.id} o={o} tracking={tracking} onRefund={(id,amount)=>void requestRefund(id,amount)} />)}{requests.map(r=><View key={r.id} style={s.card}><Text style={s.title}>جيب ليا</Text><Text>{r.request_title}</Text><Text style={s.muted}>{r.status}</Text></View>)}</>}
 {tab==="cart"&&<><Text style={s.h1}>السلة</Text>{cart.map(i=><View key={i.product.id} style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.title}>{i.product.name_ar}{i.variant?" · "+i.variant.name_ar:""}</Text><Text>{money(i.variant?.price_minor??i.product.price_minor)} × {i.quantity}</Text></View><View style={s.row}><Pressable onPress={()=>qty(i.product.id,-1)}><Text style={s.big}>−</Text></Pressable><Text>{i.quantity}</Text><Pressable onPress={()=>qty(i.product.id,1)}><Text style={s.big}>+</Text></Pressable></View></View></View>)}<Addresses data={addresses} selected={address} setSelected={setAddress} locate={locate}/><View style={s.card}><Text style={s.title}>ملخص الطلب</Text><View style={s.row}><Text>المنتجات</Text><Text>{money(subtotal)}</Text></View><View style={s.row}><Text>التوصيل</Text><Text>{quote?money(quote.delivery_fee_minor):"..."}</Text></View><View style={s.row}><Text>رسوم الخدمة</Text><Text>{quote?money(quote.service_fee_minor):"..."}</Text></View><View style={s.row}><Text>البقشيش</Text><Text>{money(tip)}</Text></View><Text style={s.section}>اختار البقشيش</Text><View style={s.row}>{[0,500,1000,2000].map(v=><Pressable key={v} onPress={()=>setTip(v)} style={[s.chip,tip===v&&s.addressActive]}><Text>{v===0?"لا":money(v)}</Text></Pressable>)}</View><View style={[s.row,{marginTop:10}]}><Text style={s.title}>المجموع النهائي</Text><Text style={s.price}>{quote?money(quote.total_minor):"..."}</Text></View><Text style={s.section}>طريقة الدفع</Text><View style={s.row}><Pressable onPress={()=>setPaymentMethod("cod")} style={[s.chip,paymentMethod==="cod"&&s.addressActive]}><Text>الدفع عند الاستلام</Text></Pressable>{ONLINE_PAYMENTS_ENABLED&&<Pressable onPress={()=>setPaymentMethod("online")} style={[s.chip,paymentMethod==="online"&&s.addressActive]}><Text>الدفع الإلكتروني</Text></Pressable>}</View><Text style={s.muted}>{ONLINE_PAYMENTS_ENABLED&&paymentMethod==="online"?"غادي يتأكد الطلب ملي يتم الدفع.":"الدفع عند الاستلام"}{quote?.eta_seconds?` · ETA ${Math.max(1,Math.round(quote.eta_seconds/60))} د`:""}</Text><Btn title={busy?"...":"تأكيد الطلب"} onPress={()=>void checkout()} disabled={busy||!cart.length||!quote}/></View></>}
 {tab==="profile"&&<><Text style={s.h1}>حسابي</Text><Addresses data={addresses} selected={address} setSelected={setAddress} locate={locate}/><Btn title="خروج" light onPress={()=>void supabase.auth.signOut()}/></>}
 {err?<Text style={s.err}>{err}</Text>:null}{busy||false?<ActivityIndicator style={{margin:12}}/>:null}</ScrollView><View style={s.tabs}>{([["home","الرئيسية"],["search","بحث"],["orders","طلباتي"],["cart","السلة"],["profile","حسابي"]] as const).map(([k,v])=><Pressable key={k} onPress={()=>setTab(k)}><Text style={tab===k?s.active:s.tab}>{v}</Text></Pressable>)}</View></SafeAreaView>}
function OrderCard({o,tracking,onRefund}:{o:Order;tracking:Record<string,{latitude:number;longitude:number;recorded_at:string;status:string;eta_seconds:number|null;distance_meters:number|null}>;onRefund:(id:string,amount:number)=>void}){const d=o.deliveries?.[0];const live=d&&tracking[d.id];const active=!!d&&["assigned","accepted","at_pickup","picked_up","in_transit"].includes(d.status??"");async function maps(){const p=live?{latitude:live.latitude,longitude:live.longitude}:{latitude:d?.delivery_latitude,longitude:d?.delivery_longitude};if(p?.latitude==null||p.longitude==null)return;await Linking.openURL("https://www.google.com/maps/search/?api=1&query="+p.latitude+","+p.longitude)}return <View style={s.card}><View style={s.row}><Text style={s.title}>{o.master_order_number??o.order_number??"طلب"}</Text><Text>{awaitingPayment(o)?"في انتظار الدفع":orderStatusLabel(o.status)}</Text></View><Text style={s.price}>{money(o.total_minor??0)}</Text>{d?<><Text style={s.muted}>{d.delivery_address_text}</Text><View style={s.track}><View><Text style={s.trackLabel}>{active?"التوصيل جاري":"حالة التوصيل"}</Text><Text style={s.trackStatus}>{deliveryStatusLabel(d.status)}{d.eta_seconds?" · "+Math.max(1,Math.round(d.eta_seconds/60))+" د":""}</Text></View>{active?<Btn title={live?"تتبع مباشر":"الموقع"} onPress={()=>void maps()}/>:null}</View>{live?<Text style={s.live}>● LIVE · آخر تحديث {new Date(live.recorded_at).toLocaleTimeString("fr-MA",{hour:"2-digit",minute:"2-digit"})}</Text>:null}</>:null}</View>}
function Product({p,add}:{p:Product;add:(v?:Variant)=>void}){const[variant,setVariant]=useState<string|undefined>();const selected=p.variants?.find(v=>v.id===variant);const price=selected?.price_minor??p.price_minor;return <View style={s.card}><View style={s.row}><View style={{flex:1}}><Text style={s.title}>{p.name_ar}</Text><Text style={s.muted}>{p.name_fr}</Text>{p.description_ar?<Text style={s.muted}>{p.description_ar}</Text>:null}<Text style={s.price}>{money(price)}</Text></View><Btn title="+" onPress={()=>add(selected)} disabled={!p.is_available||!!p.variants?.length&&!selected}/></View>{p.variants?.length?<ScrollView horizontal style={{marginTop:8}}>{p.variants.map(v=><Pressable key={v.id} onPress={()=>setVariant(v.id)} style={[s.chip,variant===v.id&&s.addressActive]}><Text>{v.name_ar} · {money(v.price_minor)}</Text></Pressable>)}</ScrollView>:null}</View>}
function Addresses({data,selected,setSelected,locate}:{data:Address[];selected:string|null;setSelected:(v:string)=>void;locate:()=>void}){return <View style={{marginVertical:8}}><View style={s.row}><Text style={s.title}>عنوان التوصيل</Text><Pressable onPress={locate}><Text style={s.link}>+ موقعي</Text></Pressable></View>{data.map(a=><Pressable key={a.id} onPress={()=>setSelected(a.id)} style={[s.address,selected===a.id&&s.addressActive]}><View style={{flex:1}}><Text style={s.title}>{a.label||"العنوان"}</Text><Text style={s.muted}>{a.address_text}</Text></View><Text>{selected===a.id?"●":"○"}</Text></Pressable>)}</View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f5f7fa"},auth:{padding:22,flex:1,justifyContent:"center"},logo:{fontSize:42,fontWeight:"900",color:"#172033"},brand:{fontSize:25,fontWeight:"900",color:"#172033"},muted:{color:"#64748b",lineHeight:20},h1:{fontSize:28,fontWeight:"900",color:"#172033",marginBottom:10},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#d9e0e8",borderRadius:13,padding:13,marginVertical:6},btn:{backgroundColor:"#172033",paddingVertical:11,paddingHorizontal:16,borderRadius:12,alignSelf:"flex-start",marginVertical:6},btnLight:{backgroundColor:"#fff",borderWidth:1,borderColor:"#d9e0e8"},btnText:{color:"#fff",fontWeight:"900"},btnLightText:{color:"#172033"},disabled:{opacity:.45},err:{backgroundColor:"#fff1f2",color:"#9f1239",padding:10,borderRadius:10,marginVertical:8},link:{fontWeight:"900",color:"#172033",paddingVertical:8},head:{padding:17,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},kicker:{fontSize:11,fontWeight:"900",color:"#64748b",letterSpacing:1.5},headTitle:{fontSize:24,fontWeight:"900",color:"#172033"},cart:{fontSize:20},pad:{padding:17,paddingBottom:110},banner:{backgroundColor:"#172033",borderRadius:20,padding:20,marginBottom:18},bannerTitle:{color:"#fff",fontSize:29,fontWeight:"900"},bannerText:{color:"#cbd5e1",marginTop:4},section:{fontSize:19,fontWeight:"900",color:"#172033",marginVertical:10},chip:{backgroundColor:"#fff",padding:10,borderRadius:20,marginRight:8},card:{backgroundColor:"#fff",borderRadius:16,borderWidth:1,borderColor:"#e5eaf0",padding:14,marginBottom:10},title:{fontWeight:"900",color:"#172033",fontSize:15},price:{fontWeight:"900",fontSize:17,color:"#172033",marginTop:4},row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10},big:{fontSize:24,fontWeight:"900",paddingHorizontal:8},address:{backgroundColor:"#fff",borderWidth:1,borderColor:"#e1e7ed",borderRadius:13,padding:12,marginVertical:5,flexDirection:"row",alignItems:"center"},addressActive:{borderColor:"#172033"},track:{backgroundColor:"#f1f5f9",borderRadius:14,padding:12,flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:8},trackLabel:{color:"#64748b",fontSize:11,fontWeight:"800"},trackStatus:{color:"#172033",fontSize:14,fontWeight:"900",marginTop:2},live:{color:"#059669",fontSize:11,fontWeight:"800",marginTop:6},tabs:{position:"absolute",bottom:0,left:0,right:0,backgroundColor:"#fff",padding:12,borderTopWidth:1,borderTopColor:"#e5eaf0",flexDirection:"row",justifyContent:"space-around"},tab:{color:"#64748b",fontWeight:"700"},active:{color:"#172033",fontWeight:"900"}});
