import { createRequestContext, isAuthenticated } from "./lib/request-context";
import { authorize } from "./lib/authorization";
import { PERMISSIONS } from "./lib/permissions";
import { errorResponse, successResponse } from "./lib/response";
import { databaseDelete, databaseGet, databaseInsert, databaseUpdate, type DatabaseEnv } from "./lib/database";

function tokenOf(request:Request){const v=request.headers.get("Authorization")??"";return v.startsWith("Bearer ")?v.slice(7):"";}
function fail(code:string,message:string,status:number,requestId:string){return errorResponse({code,message,status},requestId);}
function uuidLike(v:unknown){return typeof v==="string"&&/^[0-9a-f-]{36}$/i.test(v);}
function text(v:unknown,max:number){return v==null?null:typeof v==="string"&&v.trim().length<=max?v.trim():undefined;}
function number(v:unknown,min:number,max:number){return typeof v==="number"&&Number.isFinite(v)&&v>=min&&v<=max?v:null;}

export async function routeCustomer(request:Request,env:unknown,requestId:string):Promise<Response|null>{
 const u=new URL(request.url),path=u.pathname.replace(/^\/api\/v1\/?/,"").split("/").filter(Boolean),method=request.method.toUpperCase();
 if(path[0]!=="customer")return null;
 const context=await createRequestContext(request,env as Parameters<typeof createRequestContext>[1]);
 if(!isAuthenticated(context))return fail("UNAUTHORIZED",context.error??"Authentication required",401,requestId);
 const token=tokenOf(request),uid=context.user!.id,db=env as DatabaseEnv;
 if(path[1]!=="me")return null;
 const denied=authorize(context,PERMISSIONS.CUSTOMER_PROFILE_READ);if(denied.allowed===false)return fail("FORBIDDEN",denied.reason??"Permission denied",403,requestId);
 if(path[2]==="orders"&&method==="GET"&&path.length===3){const r=await databaseGet<unknown[]>(`/rest/v1/master_orders?select=id,order_number,status,total_minor,created_at,deliveries(id,status,eta_seconds,delivery_address_text,delivery_latitude,delivery_longitude)&customer_id=eq.${uid}&order=created_at.desc&limit=50`,db,token);if(r.error)return fail("CUSTOMER_ORDERS_ERROR",r.error,502,requestId);return successResponse(r.data??[],{requestId});}
 if(path[2]==="addresses"&&method==="GET"&&path.length===3){const r=await databaseGet<unknown[]>(`/rest/v1/addresses?select=*&user_id=eq.${uid}&is_active=eq.true&order=is_default.desc,created_at.desc`,db,token);if(r.error)return fail("CUSTOMER_ADDRESSES_ERROR",r.error,502,requestId);return successResponse(r.data??[],{requestId});}
 if(path[2]==="addresses"&&method==="POST"&&path.length===3){const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body||typeof body!=="object")return fail("VALIDATION_ERROR","Invalid JSON body",400,requestId);const address_text=text(body.address_text,500),label=text(body.label,80),apartment=text(body.apartment,80),floor=text(body.floor,40),landmark=text(body.landmark,200),delivery_note=text(body.delivery_note,500),lat=number(body.latitude,-90,90),lng=number(body.longitude,-180,180);if(!address_text||lat===null||lng===null)return fail("VALIDATION_ERROR","address_text, latitude and longitude are required",400,requestId);if([label,apartment,floor,landmark,delivery_note].some(v=>v===undefined))return fail("VALIDATION_ERROR","Invalid address field",400,requestId);const r=await databaseInsert<unknown[]>("/rest/v1/addresses",db,{user_id:uid,label,address_text,apartment,floor,landmark,delivery_note,latitude:lat,longitude:lng,is_default:body.is_default===true,is_active:true},token);if(r.error)return fail("CUSTOMER_ADDRESS_CREATE_ERROR",r.error,409,requestId);return successResponse(r.data?.[0]??null,{requestId});}
 const addressId=path[3];if(path[2]==="addresses"&&addressId&&uuidLike(addressId)&&method==="PATCH"&&path.length===4){const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body||typeof body!=="object")return fail("VALIDATION_ERROR","Invalid JSON body",400,requestId);const updates:Record<string,unknown>={};for(const k of ["label","address_text","apartment","floor","landmark","delivery_note"]){if(body[k]!==undefined){const v=text(body[k],k==="address_text"?500:k==="delivery_note"?500:200);if(v===undefined)return fail("VALIDATION_ERROR",`Invalid ${k}`,400,requestId);updates[k]=v;}}for(const k of ["latitude","longitude"]){if(body[k]!==undefined){const v=number(body[k],k==="latitude"?-90:-180,k==="latitude"?90:180);if(v===null)return fail("VALIDATION_ERROR",`Invalid ${k}`,400,requestId);updates[k]=v;}}if(body.is_default!==undefined){if(typeof body.is_default!=="boolean")return fail("VALIDATION_ERROR","is_default must be boolean",400,requestId);updates.is_default=body.is_default;}if(Object.keys(updates).length===0)return fail("VALIDATION_ERROR","No changes supplied",400,requestId);const r=await databaseUpdate<unknown[]>(`/rest/v1/addresses?id=eq.${addressId}&user_id=eq.${uid}`,db,updates,token);if(r.error)return fail("CUSTOMER_ADDRESS_UPDATE_ERROR",r.error,409,requestId);return successResponse(r.data?.[0]??null,{requestId});}
 if(path[2]==="addresses"&&addressId&&uuidLike(addressId)&&method==="DELETE"&&path.length===4){const r=await databaseDelete<unknown[]>(`/rest/v1/addresses?id=eq.${addressId}&user_id=eq.${uid}`,db,token);if(r.error)return fail("CUSTOMER_ADDRESS_DELETE_ERROR",r.error,409,requestId);return successResponse({deleted:true},{requestId});}
 if(path[2]==="deliveries"&&path[3]&&uuidLike(path[3])&&method==="GET"&&path.length===4){const deliveryId=path[3];const r=await databaseGet<unknown[]>(`/rest/v1/rider_locations?select=id,rider_id,delivery_id,latitude,longitude,accuracy_meters,speed_mps,heading,recorded_at&delivery_id=eq.${deliveryId}&order=recorded_at.desc&limit=1`,db,token);if(r.error)return fail("CUSTOMER_TRACKING_ERROR",r.error,502,requestId);return successResponse(r.data?.[0]??null,{requestId});}
 return null;
}
