import { createRequestContext, isAuthenticated } from "./lib/request-context";
import { authorize } from "./lib/authorization";
import { PERMISSIONS } from "./lib/permissions";
import { errorResponse, successResponse } from "./lib/response";
import { recordRiderLocation } from "./services/rider-location-service";
import { getRiderEarnings } from "./services/finance-service";
import { databaseGet, databaseInsert, type DatabaseEnv } from "./lib/database";
import { servicePost, type ServiceAuthEnv } from "./lib/service-client";
import { respondToAssignment } from "./services/dispatch-service";
function tokenOf(request: Request) { const value=request.headers.get("Authorization")??""; return value.startsWith("Bearer ")?value.slice(7):""; }
function fail(code:string,message:string,status:number,requestId:string){return errorResponse({code,message,status},requestId);}
async function bodyOf(request:Request):Promise<Record<string,unknown>>{try{const value=await request.json();return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}catch{return {};}}
function numberField(body:Record<string,unknown>,key:string,min:number,max:number){const value=body[key];return typeof value==="number"&&Number.isFinite(value)&&value>=min&&value<=max?value:null;}
function uuidLike(value:unknown){return typeof value==="string"&&/^[0-9a-f-]{36}$/i.test(value);}
function validTime(value:unknown){return typeof value==="string"&&/^([01][0-9]|2[0-3]):[0-5][0-9]$/.test(value);}
function validDate(value:unknown){return typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value);}
interface RiderRow{id:string;status:string|null;vehicle_type:string|null;vehicle_plate:string|null;is_online:boolean;}
interface AssignmentRow{id:string;delivery_id:string;rider_id:string;status:string|null;offered_at:string|null;responded_at?:string|null;}
interface DeliveryRow{id:string;master_order_id:string;delivery_address_text:string;delivery_latitude:number|null;delivery_longitude:number|null;status:string|null;eta_seconds:number|null;}
interface SlotRow{id:string;slot_date:string;start_time:string;end_time:string;capacity:number;status:string;}
interface WaitlistRow{id:string;slot_id:string;rider_id:string;position:number|null;status:string;}
interface WalletRow{id:string;balance_minor:string|number;currency:string;status:string;}
interface PerformanceRow{id:string;period_start:string;period_end:string;completed_deliveries:number;cancelled_deliveries:number;late_deliveries:number;acceptance_rate:number|null;completion_rate:number|null;average_delivery_minutes:number|null;customer_rating:number|null;calculated_at:string;}
export async function routeRider(request:Request,env:unknown,requestId:string):Promise<Response|null>{
 const url=new URL(request.url),path=url.pathname.replace(/^\/api\/v1\/?/,"").split("/").filter(Boolean),method=request.method.toUpperCase();
 const isRiderRoute=path[0]==="rider"&&path[1]==="me",isSlotRoute=path[0]==="rider-slots"; if(!isRiderRoute&&!isSlotRoute)return null;
 const context=await createRequestContext(request,env as Parameters<typeof createRequestContext>[1]); if(!isAuthenticated(context))return fail("UNAUTHORIZED",context.error??"Authentication required",401,requestId);
 const token=tokenOf(request),dbEnv=env as DatabaseEnv,serviceEnv=env as ServiceAuthEnv,riderId=context.user!.id;
 if(isSlotRoute){
   const readDecision=authorize(context,PERMISSIONS.RIDER_SLOTS_READ),writeDecision=authorize(context,PERMISSIONS.RIDER_SLOTS_BOOK);
   if(method==="GET"&&path.length===1){if(!readDecision.allowed)return fail("FORBIDDEN",readDecision.reason??"Permission denied",403,requestId);const result=await databaseGet<SlotRow[]>("/rest/v1/rider_slots?select=id,slot_date,start_time,end_time,capacity,status&status=neq.cancelled&order=slot_date.asc,start_time.asc",dbEnv,token);if(result.error)return fail("RIDER_SLOTS_ERROR",result.error,502,requestId);return successResponse(result.data??[],{requestId});}
   if(method==="POST"&&path.length===1){if(!writeDecision.allowed)return fail("FORBIDDEN",writeDecision.reason??"Permission denied",403,requestId);const body=await bodyOf(request),slotDate=body.slot_date,startTime=body.start_time,endTime=body.end_time,capacity=numberField(body,"capacity",1,20);if(!validDate(slotDate)||!validTime(startTime)||!validTime(endTime)||capacity===null)return fail("VALIDATION_ERROR","Valid slot date, times and capacity are required",400,requestId);const result=await servicePost<SlotRow>("/rest/v1/rpc/rider_create_slot",serviceEnv,{p_rider_id:riderId,p_slot_date:slotDate,p_start_time:startTime,p_end_time:endTime,p_capacity:Math.trunc(capacity)});if(result.error)return fail("RIDER_SLOT_CREATE_ERROR",result.error,409,requestId);return successResponse(Array.isArray(result.data)?result.data[0]:result.data,{requestId});}
   if(method==="POST"&&path.length===3&&path[2]==="book"){if(!writeDecision.allowed)return fail("FORBIDDEN",writeDecision.reason??"Permission denied",403,requestId);const slotId=path[1];if(!uuidLike(slotId))return fail("VALIDATION_ERROR","Invalid slot id",400,requestId);const result=await servicePost<unknown>("/rest/v1/rpc/rider_book_slot",serviceEnv,{p_rider_id:riderId,p_slot_id:slotId});if(result.error)return fail("RIDER_SLOT_BOOKING_ERROR",result.error,409,requestId);return successResponse(Array.isArray(result.data)?result.data[0]:result.data,{requestId});}
   if(method==="POST"&&path.length===3&&path[2]==="waitlist"){if(!writeDecision.allowed)return fail("FORBIDDEN",writeDecision.reason??"Permission denied",403,requestId);const slotId=path[1];if(!uuidLike(slotId))return fail("VALIDATION_ERROR","Invalid slot id",400,requestId);const result=await servicePost<WaitlistRow>("/rest/v1/rpc/rider_join_slot_waitlist",serviceEnv,{p_rider_id:riderId,p_slot_id:slotId});if(result.error)return fail("RIDER_WAITLIST_ERROR",result.error,409,requestId);return successResponse(Array.isArray(result.data)?result.data[0]:result.data,{requestId});}
   return null;
 }
 if(method==="GET"&&path.length===2){const decision=authorize(context,PERMISSIONS.RIDER_PROFILE_READ);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const result=await databaseGet<RiderRow[]>(`/rest/v1/riders?id=eq.${riderId}&select=id,status,vehicle_type,vehicle_plate,is_online`,dbEnv,token);if(result.error)return fail("RIDER_PROFILE_ERROR",result.error,502,requestId);return successResponse(result.data?.[0]??null,{requestId});}
 if(method==="GET"&&path[2]==="assignments"){const decision=authorize(context,PERMISSIONS.RIDER_DELIVERIES_READ);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const result=await databaseGet<AssignmentRow[]>(`/rest/v1/delivery_assignments?rider_id=eq.${riderId}&select=id,delivery_id,rider_id,status,offered_at,responded_at&order=offered_at.desc`,dbEnv,token);if(result.error)return fail("RIDER_ASSIGNMENTS_ERROR",result.error,502,requestId);return successResponse(result.data??[],{requestId});}
 if(method==="GET"&&path[2]==="deliveries"){const decision=authorize(context,PERMISSIONS.RIDER_DELIVERIES_READ);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const assignments=await databaseGet<AssignmentRow[]>(`/rest/v1/delivery_assignments?rider_id=eq.${riderId}&select=delivery_id&order=offered_at.desc`,dbEnv,token);if(assignments.error)return fail("RIDER_DELIVERIES_ERROR",assignments.error,502,requestId);const ids=[...new Set((assignments.data??[]).map(x=>x.delivery_id).filter(uuidLike))];if(!ids.length)return successResponse([],{requestId});const result=await databaseGet<DeliveryRow[]>(`/rest/v1/deliveries?select=id,master_order_id,delivery_address_text,delivery_latitude,delivery_longitude,status,eta_seconds&id=in.(${ids.join(",")})&order=created_at.desc`,dbEnv,token);if(result.error)return fail("RIDER_DELIVERIES_ERROR",result.error,502,requestId);return successResponse(result.data??[],{requestId});}
 if(method==="GET"&&path[2]==="earnings"){const decision=authorize(context,PERMISSIONS.WALLET_READ);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const result=await getRiderEarnings(riderId,env as any,token);if(!result.success)return fail("RIDER_EARNINGS_ERROR",result.error??"Unable to load earnings",502,requestId);const rows=result.data??[];let total=0n,pending=0n,paid=0n;for(const row of rows){const amount=BigInt(row.total_minor||"0");total+=amount;if(["pending","accrued","processing"].includes(row.status))pending+=amount;if(["paid","settled"].includes(row.status))paid+=amount;}return successResponse({total_minor:total.toString(),pending_minor:pending.toString(),paid_minor:paid.toString(),currency:"MAD",entries:rows},{requestId});}
 if(method==="GET"&&path[2]==="wallet"){const decision=authorize(context,PERMISSIONS.WALLET_READ);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const result=await databaseGet<WalletRow[]>(`/rest/v1/wallets?select=id,balance_minor,currency,status&user_id=eq.${riderId}&limit=1`,dbEnv,token);if(result.error)return fail("RIDER_WALLET_ERROR",result.error,502,requestId);return successResponse(result.data?.[0]??null,{requestId});}
 if(method==="GET"&&path[2]==="performance"){const decision=authorize(context,PERMISSIONS.RIDER_PERFORMANCE_READ);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const result=await databaseGet<PerformanceRow[]>(`/rest/v1/rider_performance?rider_id=eq.${riderId}&select=id,period_start,period_end,completed_deliveries,cancelled_deliveries,late_deliveries,acceptance_rate,completion_rate,average_delivery_minutes,customer_rating,calculated_at&order=period_start.desc&limit=12`,dbEnv,token);if(result.error)return fail("RIDER_PERFORMANCE_ERROR",result.error,502,requestId);return successResponse(result.data??[],{requestId});}
 if(method==="POST"&&path[2]==="online"){const decision=authorize(context,PERMISSIONS.RIDER_PROFILE_UPDATE);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const body=await bodyOf(request);if(typeof body.is_online!=="boolean")return fail("VALIDATION_ERROR","is_online must be boolean",400,requestId);const result=await servicePost<unknown>("/rest/v1/rpc/rider_set_online",serviceEnv,{p_rider_id:riderId,p_is_online:body.is_online});if(result.error)return fail("RIDER_ONLINE_ERROR",result.error,409,requestId);return successResponse(Array.isArray(result.data)?result.data[0]:result.data,{requestId});}
 if(method==="POST"&&path[2]==="assignments"&&path.length===5&&path[4]==="respond"){const decision=authorize(context,PERMISSIONS.RIDER_DELIVERIES_UPDATE);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const assignmentId=path[3];if(!uuidLike(assignmentId))return fail("VALIDATION_ERROR","Invalid assignment id",400,requestId);const body=await bodyOf(request);if(body.status!=="accepted"&&body.status!=="rejected")return fail("VALIDATION_ERROR","Invalid assignment response",400,requestId);const result=await respondToAssignment(assignmentId,riderId,body.status,serviceEnv);if(!result.success)return fail("ASSIGNMENT_RESPONSE_ERROR",result.error??"Unable to respond",409,requestId);return successResponse(result.data,{requestId});}
 if(method==="POST"&&path[2]==="deliveries"&&path.length===5&&path[4]==="status"){const decision=authorize(context,PERMISSIONS.RIDER_DELIVERIES_UPDATE);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const deliveryId=path[3];if(!uuidLike(deliveryId))return fail("VALIDATION_ERROR","Invalid delivery id",400,requestId);const body=await bodyOf(request),allowed=["at_pickup","picked_up","in_transit","delivered","failed","cancelled"];if(typeof body.status!=="string"||!allowed.includes(body.status))return fail("VALIDATION_ERROR","Invalid delivery status",400,requestId);const reason=typeof body.reason==="string"?body.reason.slice(0,500):null;const result=await servicePost<unknown>("/rest/v1/rpc/rider_transition_delivery_status",serviceEnv,{p_delivery_id:deliveryId,p_rider_id:riderId,p_new_status:body.status,p_reason:reason});if(result.error)return fail("DELIVERY_STATUS_ERROR",result.error,409,requestId);return successResponse(Array.isArray(result.data)?result.data[0]:result.data,{requestId});}
 if(method==="POST"&&path[2]==="location"){const decision=authorize(context,PERMISSIONS.RIDER_LOCATION_UPDATE);if(!decision.allowed)return fail("FORBIDDEN",decision.reason??"Permission denied",403,requestId);const body=await bodyOf(request),latitude=numberField(body,"latitude",-90,90),longitude=numberField(body,"longitude",-180,180),accuracy=body.accuracy_meters==null?null:numberField(body,"accuracy_meters",0,10000),speed=body.speed_mps==null?null:numberField(body,"speed_mps",0,100),heading=body.heading==null?null:numberField(body,"heading",0,360),deliveryId=typeof body.delivery_id==="string"&&body.delivery_id.length<=64?body.delivery_id:null;if(latitude===null||longitude===null||!uuidLike(deliveryId)||(body.accuracy_meters!=null&&accuracy===null)||(body.speed_mps!=null&&speed===null)||(body.heading!=null&&heading===null))return fail("VALIDATION_ERROR","Active delivery id and valid location payload are required",400,requestId);const result=await recordRiderLocation(riderId,env as any,token,{delivery_id:deliveryId,latitude,longitude,accuracy_meters:accuracy,speed_mps:speed,heading});if(!result.success)return fail("RIDER_LOCATION_ERROR",result.error??"Unable to record location",502,requestId);return successResponse(result.data,{requestId});}
 return null;
}
