name = "wasslha-api"
main = "src/index.ts"
compatibility_date = "2026-09-01"

[vars]
ENVIRONMENT = "development"

[[ratelimits]]
name = "API_RATE_LIMITER"
namespace_id = "1001"

  [ratelimits.simple]
  limit = 100
  period = 60
